// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.9
// 	protoc        v6.32.1
// source: indexer.proto

package indexer_grpc_client

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserTradeHistoryType int32

const (
	UserTradeHistoryType_FILL_TRADE   UserTradeHistoryType = 0
	UserTradeHistoryType_LIMIT_TRADE  UserTradeHistoryType = 1
	UserTradeHistoryType_MARKET_TRADE UserTradeHistoryType = 2
	UserTradeHistoryType_SWEEP_TRADE  UserTradeHistoryType = 3
)

// Enum value maps for UserTradeHistoryType.
var (
	UserTradeHistoryType_name = map[int32]string{
		0: "FILL_TRADE",
		1: "LIMIT_TRADE",
		2: "MARKET_TRADE",
		3: "SWEEP_TRADE",
	}
	UserTradeHistoryType_value = map[string]int32{
		"FILL_TRADE":   0,
		"LIMIT_TRADE":  1,
		"MARKET_TRADE": 2,
		"SWEEP_TRADE":  3,
	}
)

func (x UserTradeHistoryType) Enum() *UserTradeHistoryType {
	p := new(UserTradeHistoryType)
	*p = x
	return p
}

func (x UserTradeHistoryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserTradeHistoryType) Descriptor() protoreflect.EnumDescriptor {
	return file_indexer_proto_enumTypes[0].Descriptor()
}

func (UserTradeHistoryType) Type() protoreflect.EnumType {
	return &file_indexer_proto_enumTypes[0]
}

func (x UserTradeHistoryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserTradeHistoryType.Descriptor instead.
func (UserTradeHistoryType) EnumDescriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{0}
}

type UserOrderHistoryStatus int32

const (
	UserOrderHistoryStatus_CANCELED_ORDER UserOrderHistoryStatus = 0
	UserOrderHistoryStatus_FILLED_ORDER   UserOrderHistoryStatus = 1
)

// Enum value maps for UserOrderHistoryStatus.
var (
	UserOrderHistoryStatus_name = map[int32]string{
		0: "CANCELED_ORDER",
		1: "FILLED_ORDER",
	}
	UserOrderHistoryStatus_value = map[string]int32{
		"CANCELED_ORDER": 0,
		"FILLED_ORDER":   1,
	}
)

func (x UserOrderHistoryStatus) Enum() *UserOrderHistoryStatus {
	p := new(UserOrderHistoryStatus)
	*p = x
	return p
}

func (x UserOrderHistoryStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserOrderHistoryStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_indexer_proto_enumTypes[1].Descriptor()
}

func (UserOrderHistoryStatus) Type() protoreflect.EnumType {
	return &file_indexer_proto_enumTypes[1]
}

func (x UserOrderHistoryStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserOrderHistoryStatus.Descriptor instead.
func (UserOrderHistoryStatus) EnumDescriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{1}
}

type UserLiquidityHistoryType int32

const (
	UserLiquidityHistoryType_ADD_LIQUIDITY    UserLiquidityHistoryType = 0
	UserLiquidityHistoryType_REMOVE_LIQUIDITY UserLiquidityHistoryType = 1
)

// Enum value maps for UserLiquidityHistoryType.
var (
	UserLiquidityHistoryType_name = map[int32]string{
		0: "ADD_LIQUIDITY",
		1: "REMOVE_LIQUIDITY",
	}
	UserLiquidityHistoryType_value = map[string]int32{
		"ADD_LIQUIDITY":    0,
		"REMOVE_LIQUIDITY": 1,
	}
)

func (x UserLiquidityHistoryType) Enum() *UserLiquidityHistoryType {
	p := new(UserLiquidityHistoryType)
	*p = x
	return p
}

func (x UserLiquidityHistoryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserLiquidityHistoryType) Descriptor() protoreflect.EnumDescriptor {
	return file_indexer_proto_enumTypes[2].Descriptor()
}

func (UserLiquidityHistoryType) Type() protoreflect.EnumType {
	return &file_indexer_proto_enumTypes[2]
}

func (x UserLiquidityHistoryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserLiquidityHistoryType.Descriptor instead.
func (UserLiquidityHistoryType) EnumDescriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{2}
}

type GetUserFundingType int32

const (
	GetUserFundingType_FUNDING_PAID     GetUserFundingType = 0
	GetUserFundingType_FUNDING_RECEIVED GetUserFundingType = 1
)

// Enum value maps for GetUserFundingType.
var (
	GetUserFundingType_name = map[int32]string{
		0: "FUNDING_PAID",
		1: "FUNDING_RECEIVED",
	}
	GetUserFundingType_value = map[string]int32{
		"FUNDING_PAID":     0,
		"FUNDING_RECEIVED": 1,
	}
)

func (x GetUserFundingType) Enum() *GetUserFundingType {
	p := new(GetUserFundingType)
	*p = x
	return p
}

func (x GetUserFundingType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetUserFundingType) Descriptor() protoreflect.EnumDescriptor {
	return file_indexer_proto_enumTypes[3].Descriptor()
}

func (GetUserFundingType) Type() protoreflect.EnumType {
	return &file_indexer_proto_enumTypes[3]
}

func (x GetUserFundingType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetUserFundingType.Descriptor instead.
func (GetUserFundingType) EnumDescriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{3}
}

type GetUserInstrumentTransferHistoryType int32

const (
	GetUserInstrumentTransferHistoryType_SCATTER GetUserInstrumentTransferHistoryType = 0
	GetUserInstrumentTransferHistoryType_GATHER  GetUserInstrumentTransferHistoryType = 1
)

// Enum value maps for GetUserInstrumentTransferHistoryType.
var (
	GetUserInstrumentTransferHistoryType_name = map[int32]string{
		0: "SCATTER",
		1: "GATHER",
	}
	GetUserInstrumentTransferHistoryType_value = map[string]int32{
		"SCATTER": 0,
		"GATHER":  1,
	}
)

func (x GetUserInstrumentTransferHistoryType) Enum() *GetUserInstrumentTransferHistoryType {
	p := new(GetUserInstrumentTransferHistoryType)
	*p = x
	return p
}

func (x GetUserInstrumentTransferHistoryType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GetUserInstrumentTransferHistoryType) Descriptor() protoreflect.EnumDescriptor {
	return file_indexer_proto_enumTypes[4].Descriptor()
}

func (GetUserInstrumentTransferHistoryType) Type() protoreflect.EnumType {
	return &file_indexer_proto_enumTypes[4]
}

func (x GetUserInstrumentTransferHistoryType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GetUserInstrumentTransferHistoryType.Descriptor instead.
func (GetUserInstrumentTransferHistoryType) EnumDescriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{4}
}

type DepositWithdrawType int32

const (
	DepositWithdrawType_DEPOSIT  DepositWithdrawType = 0
	DepositWithdrawType_WITHDRAW DepositWithdrawType = 1
)

// Enum value maps for DepositWithdrawType.
var (
	DepositWithdrawType_name = map[int32]string{
		0: "DEPOSIT",
		1: "WITHDRAW",
	}
	DepositWithdrawType_value = map[string]int32{
		"DEPOSIT":  0,
		"WITHDRAW": 1,
	}
)

func (x DepositWithdrawType) Enum() *DepositWithdrawType {
	p := new(DepositWithdrawType)
	*p = x
	return p
}

func (x DepositWithdrawType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DepositWithdrawType) Descriptor() protoreflect.EnumDescriptor {
	return file_indexer_proto_enumTypes[5].Descriptor()
}

func (DepositWithdrawType) Type() protoreflect.EnumType {
	return &file_indexer_proto_enumTypes[5]
}

func (x DepositWithdrawType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DepositWithdrawType.Descriptor instead.
func (DepositWithdrawType) EnumDescriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{5}
}

type GetUserTradeHistoryResponse struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	List          []*GetUserTradeHistoryResponseDetails `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	TotalCount    uint32                                `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserTradeHistoryResponse) Reset() {
	*x = GetUserTradeHistoryResponse{}
	mi := &file_indexer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTradeHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTradeHistoryResponse) ProtoMessage() {}

func (x *GetUserTradeHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTradeHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetUserTradeHistoryResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{0}
}

func (x *GetUserTradeHistoryResponse) GetList() []*GetUserTradeHistoryResponseDetails {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetUserTradeHistoryResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetUserTradeHistoryResponseDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InstrumentAddress string                 `protobuf:"bytes,2,opt,name=instrumentAddress,proto3" json:"instrumentAddress,omitempty"`
	Expiry            uint32                 `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Size              string                 `protobuf:"bytes,4,opt,name=size,proto3" json:"size,omitempty"`
	Balance           string                 `protobuf:"bytes,5,opt,name=balance,proto3" json:"balance,omitempty"`
	Price             string                 `protobuf:"bytes,6,opt,name=price,proto3" json:"price,omitempty"`
	TradeFee          string                 `protobuf:"bytes,7,opt,name=tradeFee,proto3" json:"tradeFee,omitempty"`
	ProtocolFee       string                 `protobuf:"bytes,8,opt,name=protocolFee,proto3" json:"protocolFee,omitempty"`
	Timestamp         uint64                 `protobuf:"varint,9,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TxHash            string                 `protobuf:"bytes,10,opt,name=txHash,proto3" json:"txHash,omitempty"`
	Type              UserTradeHistoryType   `protobuf:"varint,11,opt,name=type,proto3,enum=indexer.grpc.UserTradeHistoryType" json:"type,omitempty"`
	Symbol            string                 `protobuf:"bytes,12,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BaseToken         *TokenInfo             `protobuf:"bytes,13,opt,name=baseToken,proto3" json:"baseToken,omitempty"`
	QuoteToken        *TokenInfo             `protobuf:"bytes,14,opt,name=quoteToken,proto3" json:"quoteToken,omitempty"`
	TypeString        string                 `protobuf:"bytes,15,opt,name=typeString,proto3" json:"typeString,omitempty"`
	Side              string                 `protobuf:"bytes,16,opt,name=side,proto3" json:"side,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetUserTradeHistoryResponseDetails) Reset() {
	*x = GetUserTradeHistoryResponseDetails{}
	mi := &file_indexer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserTradeHistoryResponseDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserTradeHistoryResponseDetails) ProtoMessage() {}

func (x *GetUserTradeHistoryResponseDetails) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserTradeHistoryResponseDetails.ProtoReflect.Descriptor instead.
func (*GetUserTradeHistoryResponseDetails) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserTradeHistoryResponseDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserTradeHistoryResponseDetails) GetInstrumentAddress() string {
	if x != nil {
		return x.InstrumentAddress
	}
	return ""
}

func (x *GetUserTradeHistoryResponseDetails) GetExpiry() uint32 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *GetUserTradeHistoryResponseDetails) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *GetUserTradeHistoryResponseDetails) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *GetUserTradeHistoryResponseDetails) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *GetUserTradeHistoryResponseDetails) GetTradeFee() string {
	if x != nil {
		return x.TradeFee
	}
	return ""
}

func (x *GetUserTradeHistoryResponseDetails) GetProtocolFee() string {
	if x != nil {
		return x.ProtocolFee
	}
	return ""
}

func (x *GetUserTradeHistoryResponseDetails) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetUserTradeHistoryResponseDetails) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *GetUserTradeHistoryResponseDetails) GetType() UserTradeHistoryType {
	if x != nil {
		return x.Type
	}
	return UserTradeHistoryType_FILL_TRADE
}

func (x *GetUserTradeHistoryResponseDetails) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetUserTradeHistoryResponseDetails) GetBaseToken() *TokenInfo {
	if x != nil {
		return x.BaseToken
	}
	return nil
}

func (x *GetUserTradeHistoryResponseDetails) GetQuoteToken() *TokenInfo {
	if x != nil {
		return x.QuoteToken
	}
	return nil
}

func (x *GetUserTradeHistoryResponseDetails) GetTypeString() string {
	if x != nil {
		return x.TypeString
	}
	return ""
}

func (x *GetUserTradeHistoryResponseDetails) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

type GetUserOrderHistoryResponse struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	List          []*GetUserOrderHistoryResponseDetails `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	TotalCount    uint32                                `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserOrderHistoryResponse) Reset() {
	*x = GetUserOrderHistoryResponse{}
	mi := &file_indexer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrderHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrderHistoryResponse) ProtoMessage() {}

func (x *GetUserOrderHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrderHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetUserOrderHistoryResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserOrderHistoryResponse) GetList() []*GetUserOrderHistoryResponseDetails {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetUserOrderHistoryResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetUserOrderHistoryResponseDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InstrumentAddress string                 `protobuf:"bytes,2,opt,name=instrumentAddress,proto3" json:"instrumentAddress,omitempty"`
	Expiry            uint32                 `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	PlaceTimestamp    uint64                 `protobuf:"varint,4,opt,name=placeTimestamp,proto3" json:"placeTimestamp,omitempty"`
	PlaceTxHash       string                 `protobuf:"bytes,5,opt,name=placeTxHash,proto3" json:"placeTxHash,omitempty"`
	Size              string                 `protobuf:"bytes,7,opt,name=size,proto3" json:"size,omitempty"`
	Balance           string                 `protobuf:"bytes,8,opt,name=balance,proto3" json:"balance,omitempty"`
	TakenSize         string                 `protobuf:"bytes,9,opt,name=takenSize,proto3" json:"takenSize,omitempty"`
	TakenBalance      string                 `protobuf:"bytes,10,opt,name=takenBalance,proto3" json:"takenBalance,omitempty"`
	OrderPrice        string                 `protobuf:"bytes,11,opt,name=orderPrice,proto3" json:"orderPrice,omitempty"`
	FeeRebate         string                 `protobuf:"bytes,12,opt,name=feeRebate,proto3" json:"feeRebate,omitempty"`
	Type              UserOrderHistoryStatus `protobuf:"varint,6,opt,name=type,proto3,enum=indexer.grpc.UserOrderHistoryStatus" json:"type,omitempty"`
	CancelTimestamp   uint64                 `protobuf:"varint,13,opt,name=cancelTimestamp,proto3" json:"cancelTimestamp,omitempty"`
	CancelTxHash      string                 `protobuf:"bytes,14,opt,name=cancelTxHash,proto3" json:"cancelTxHash,omitempty"`
	FillTimestamp     uint64                 `protobuf:"varint,15,opt,name=fillTimestamp,proto3" json:"fillTimestamp,omitempty"`
	FillTxHash        string                 `protobuf:"bytes,16,opt,name=fillTxHash,proto3" json:"fillTxHash,omitempty"`
	Symbol            string                 `protobuf:"bytes,17,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BaseToken         *TokenInfo             `protobuf:"bytes,18,opt,name=baseToken,proto3" json:"baseToken,omitempty"`
	QuoteToken        *TokenInfo             `protobuf:"bytes,19,opt,name=quoteToken,proto3" json:"quoteToken,omitempty"`
	TypeString        string                 `protobuf:"bytes,20,opt,name=typeString,proto3" json:"typeString,omitempty"`
	Side              string                 `protobuf:"bytes,21,opt,name=side,proto3" json:"side,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetUserOrderHistoryResponseDetails) Reset() {
	*x = GetUserOrderHistoryResponseDetails{}
	mi := &file_indexer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserOrderHistoryResponseDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserOrderHistoryResponseDetails) ProtoMessage() {}

func (x *GetUserOrderHistoryResponseDetails) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserOrderHistoryResponseDetails.ProtoReflect.Descriptor instead.
func (*GetUserOrderHistoryResponseDetails) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserOrderHistoryResponseDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserOrderHistoryResponseDetails) GetInstrumentAddress() string {
	if x != nil {
		return x.InstrumentAddress
	}
	return ""
}

func (x *GetUserOrderHistoryResponseDetails) GetExpiry() uint32 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *GetUserOrderHistoryResponseDetails) GetPlaceTimestamp() uint64 {
	if x != nil {
		return x.PlaceTimestamp
	}
	return 0
}

func (x *GetUserOrderHistoryResponseDetails) GetPlaceTxHash() string {
	if x != nil {
		return x.PlaceTxHash
	}
	return ""
}

func (x *GetUserOrderHistoryResponseDetails) GetSize() string {
	if x != nil {
		return x.Size
	}
	return ""
}

func (x *GetUserOrderHistoryResponseDetails) GetBalance() string {
	if x != nil {
		return x.Balance
	}
	return ""
}

func (x *GetUserOrderHistoryResponseDetails) GetTakenSize() string {
	if x != nil {
		return x.TakenSize
	}
	return ""
}

func (x *GetUserOrderHistoryResponseDetails) GetTakenBalance() string {
	if x != nil {
		return x.TakenBalance
	}
	return ""
}

func (x *GetUserOrderHistoryResponseDetails) GetOrderPrice() string {
	if x != nil {
		return x.OrderPrice
	}
	return ""
}

func (x *GetUserOrderHistoryResponseDetails) GetFeeRebate() string {
	if x != nil {
		return x.FeeRebate
	}
	return ""
}

func (x *GetUserOrderHistoryResponseDetails) GetType() UserOrderHistoryStatus {
	if x != nil {
		return x.Type
	}
	return UserOrderHistoryStatus_CANCELED_ORDER
}

func (x *GetUserOrderHistoryResponseDetails) GetCancelTimestamp() uint64 {
	if x != nil {
		return x.CancelTimestamp
	}
	return 0
}

func (x *GetUserOrderHistoryResponseDetails) GetCancelTxHash() string {
	if x != nil {
		return x.CancelTxHash
	}
	return ""
}

func (x *GetUserOrderHistoryResponseDetails) GetFillTimestamp() uint64 {
	if x != nil {
		return x.FillTimestamp
	}
	return 0
}

func (x *GetUserOrderHistoryResponseDetails) GetFillTxHash() string {
	if x != nil {
		return x.FillTxHash
	}
	return ""
}

func (x *GetUserOrderHistoryResponseDetails) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetUserOrderHistoryResponseDetails) GetBaseToken() *TokenInfo {
	if x != nil {
		return x.BaseToken
	}
	return nil
}

func (x *GetUserOrderHistoryResponseDetails) GetQuoteToken() *TokenInfo {
	if x != nil {
		return x.QuoteToken
	}
	return nil
}

func (x *GetUserOrderHistoryResponseDetails) GetTypeString() string {
	if x != nil {
		return x.TypeString
	}
	return ""
}

func (x *GetUserOrderHistoryResponseDetails) GetSide() string {
	if x != nil {
		return x.Side
	}
	return ""
}

type GetUserLiquidityHistoryResponse struct {
	state         protoimpl.MessageState                    `protogen:"open.v1"`
	List          []*GetUserLiquidityHistoryResponseDetails `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	TotalCount    uint32                                    `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserLiquidityHistoryResponse) Reset() {
	*x = GetUserLiquidityHistoryResponse{}
	mi := &file_indexer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLiquidityHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLiquidityHistoryResponse) ProtoMessage() {}

func (x *GetUserLiquidityHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLiquidityHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetUserLiquidityHistoryResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{4}
}

func (x *GetUserLiquidityHistoryResponse) GetList() []*GetUserLiquidityHistoryResponseDetails {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetUserLiquidityHistoryResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetUserLiquidityHistoryResponseDetails struct {
	state             protoimpl.MessageState   `protogen:"open.v1"`
	Id                string                   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InstrumentAddress string                   `protobuf:"bytes,2,opt,name=instrumentAddress,proto3" json:"instrumentAddress,omitempty"`
	Expiry            uint32                   `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Timestamp         uint64                   `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TxHash            string                   `protobuf:"bytes,5,opt,name=txHash,proto3" json:"txHash,omitempty"`
	Type              UserLiquidityHistoryType `protobuf:"varint,6,opt,name=type,proto3,enum=indexer.grpc.UserLiquidityHistoryType" json:"type,omitempty"`
	LowerTick         int64                    `protobuf:"varint,7,opt,name=lowerTick,proto3" json:"lowerTick,omitempty"`
	UpperTick         int64                    `protobuf:"varint,8,opt,name=upperTick,proto3" json:"upperTick,omitempty"`
	LowerPrice        string                   `protobuf:"bytes,9,opt,name=lowerPrice,proto3" json:"lowerPrice,omitempty"`
	UpperPrice        string                   `protobuf:"bytes,10,opt,name=upperPrice,proto3" json:"upperPrice,omitempty"`
	FairPrice         string                   `protobuf:"bytes,11,opt,name=fairPrice,proto3" json:"fairPrice,omitempty"`
	Amount            string                   `protobuf:"bytes,12,opt,name=amount,proto3" json:"amount,omitempty"`
	FeeEarned         string                   `protobuf:"bytes,13,opt,name=feeEarned,proto3" json:"feeEarned,omitempty"`
	Symbol            string                   `protobuf:"bytes,14,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BaseToken         *TokenInfo               `protobuf:"bytes,15,opt,name=baseToken,proto3" json:"baseToken,omitempty"`
	QuoteToken        *TokenInfo               `protobuf:"bytes,16,opt,name=quoteToken,proto3" json:"quoteToken,omitempty"`
	TypeString        string                   `protobuf:"bytes,17,opt,name=typeString,proto3" json:"typeString,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetUserLiquidityHistoryResponseDetails) Reset() {
	*x = GetUserLiquidityHistoryResponseDetails{}
	mi := &file_indexer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserLiquidityHistoryResponseDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserLiquidityHistoryResponseDetails) ProtoMessage() {}

func (x *GetUserLiquidityHistoryResponseDetails) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserLiquidityHistoryResponseDetails.ProtoReflect.Descriptor instead.
func (*GetUserLiquidityHistoryResponseDetails) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{5}
}

func (x *GetUserLiquidityHistoryResponseDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserLiquidityHistoryResponseDetails) GetInstrumentAddress() string {
	if x != nil {
		return x.InstrumentAddress
	}
	return ""
}

func (x *GetUserLiquidityHistoryResponseDetails) GetExpiry() uint32 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *GetUserLiquidityHistoryResponseDetails) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetUserLiquidityHistoryResponseDetails) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *GetUserLiquidityHistoryResponseDetails) GetType() UserLiquidityHistoryType {
	if x != nil {
		return x.Type
	}
	return UserLiquidityHistoryType_ADD_LIQUIDITY
}

func (x *GetUserLiquidityHistoryResponseDetails) GetLowerTick() int64 {
	if x != nil {
		return x.LowerTick
	}
	return 0
}

func (x *GetUserLiquidityHistoryResponseDetails) GetUpperTick() int64 {
	if x != nil {
		return x.UpperTick
	}
	return 0
}

func (x *GetUserLiquidityHistoryResponseDetails) GetLowerPrice() string {
	if x != nil {
		return x.LowerPrice
	}
	return ""
}

func (x *GetUserLiquidityHistoryResponseDetails) GetUpperPrice() string {
	if x != nil {
		return x.UpperPrice
	}
	return ""
}

func (x *GetUserLiquidityHistoryResponseDetails) GetFairPrice() string {
	if x != nil {
		return x.FairPrice
	}
	return ""
}

func (x *GetUserLiquidityHistoryResponseDetails) GetAmount() string {
	if x != nil {
		return x.Amount
	}
	return ""
}

func (x *GetUserLiquidityHistoryResponseDetails) GetFeeEarned() string {
	if x != nil {
		return x.FeeEarned
	}
	return ""
}

func (x *GetUserLiquidityHistoryResponseDetails) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetUserLiquidityHistoryResponseDetails) GetBaseToken() *TokenInfo {
	if x != nil {
		return x.BaseToken
	}
	return nil
}

func (x *GetUserLiquidityHistoryResponseDetails) GetQuoteToken() *TokenInfo {
	if x != nil {
		return x.QuoteToken
	}
	return nil
}

func (x *GetUserLiquidityHistoryResponseDetails) GetTypeString() string {
	if x != nil {
		return x.TypeString
	}
	return ""
}

type GetUserFundingHistoryResponse struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	List          []*GetUserFundingHistoryResponseDetails `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	TotalCount    uint32                                  `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserFundingHistoryResponse) Reset() {
	*x = GetUserFundingHistoryResponse{}
	mi := &file_indexer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFundingHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFundingHistoryResponse) ProtoMessage() {}

func (x *GetUserFundingHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFundingHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetUserFundingHistoryResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserFundingHistoryResponse) GetList() []*GetUserFundingHistoryResponseDetails {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetUserFundingHistoryResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetUserFundingHistoryResponseDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Id                string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InstrumentAddress string                 `protobuf:"bytes,2,opt,name=instrumentAddress,proto3" json:"instrumentAddress,omitempty"`
	Expiry            uint32                 `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Value             string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	ValueUsd          string                 `protobuf:"bytes,5,opt,name=valueUsd,proto3" json:"valueUsd,omitempty"`
	Timestamp         uint64                 `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TxHash            string                 `protobuf:"bytes,7,opt,name=txHash,proto3" json:"txHash,omitempty"`
	Type              GetUserFundingType     `protobuf:"varint,8,opt,name=type,proto3,enum=indexer.grpc.GetUserFundingType" json:"type,omitempty"`
	Symbol            string                 `protobuf:"bytes,9,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BaseToken         *TokenInfo             `protobuf:"bytes,10,opt,name=baseToken,proto3" json:"baseToken,omitempty"`
	QuoteToken        *TokenInfo             `protobuf:"bytes,11,opt,name=quoteToken,proto3" json:"quoteToken,omitempty"`
	TypeString        string                 `protobuf:"bytes,12,opt,name=typeString,proto3" json:"typeString,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetUserFundingHistoryResponseDetails) Reset() {
	*x = GetUserFundingHistoryResponseDetails{}
	mi := &file_indexer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserFundingHistoryResponseDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserFundingHistoryResponseDetails) ProtoMessage() {}

func (x *GetUserFundingHistoryResponseDetails) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserFundingHistoryResponseDetails.ProtoReflect.Descriptor instead.
func (*GetUserFundingHistoryResponseDetails) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserFundingHistoryResponseDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserFundingHistoryResponseDetails) GetInstrumentAddress() string {
	if x != nil {
		return x.InstrumentAddress
	}
	return ""
}

func (x *GetUserFundingHistoryResponseDetails) GetExpiry() uint32 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *GetUserFundingHistoryResponseDetails) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetUserFundingHistoryResponseDetails) GetValueUsd() string {
	if x != nil {
		return x.ValueUsd
	}
	return ""
}

func (x *GetUserFundingHistoryResponseDetails) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetUserFundingHistoryResponseDetails) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *GetUserFundingHistoryResponseDetails) GetType() GetUserFundingType {
	if x != nil {
		return x.Type
	}
	return GetUserFundingType_FUNDING_PAID
}

func (x *GetUserFundingHistoryResponseDetails) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetUserFundingHistoryResponseDetails) GetBaseToken() *TokenInfo {
	if x != nil {
		return x.BaseToken
	}
	return nil
}

func (x *GetUserFundingHistoryResponseDetails) GetQuoteToken() *TokenInfo {
	if x != nil {
		return x.QuoteToken
	}
	return nil
}

func (x *GetUserFundingHistoryResponseDetails) GetTypeString() string {
	if x != nil {
		return x.TypeString
	}
	return ""
}

type GteUserOperationCommonHistoryRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UserAddress       string                 `protobuf:"bytes,1,opt,name=userAddress,proto3" json:"userAddress,omitempty"`
	StartTimestamp    int64                  `protobuf:"varint,2,opt,name=startTimestamp,proto3" json:"startTimestamp,omitempty"`
	EndTimestamp      int64                  `protobuf:"varint,3,opt,name=endTimestamp,proto3" json:"endTimestamp,omitempty"`
	Page              uint32                 `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Size              uint32                 `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	InstrumentAddress *string                `protobuf:"bytes,6,opt,name=instrumentAddress,proto3,oneof" json:"instrumentAddress,omitempty"`
	Expiry            *uint32                `protobuf:"varint,7,opt,name=expiry,proto3,oneof" json:"expiry,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GteUserOperationCommonHistoryRequest) Reset() {
	*x = GteUserOperationCommonHistoryRequest{}
	mi := &file_indexer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GteUserOperationCommonHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GteUserOperationCommonHistoryRequest) ProtoMessage() {}

func (x *GteUserOperationCommonHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GteUserOperationCommonHistoryRequest.ProtoReflect.Descriptor instead.
func (*GteUserOperationCommonHistoryRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{8}
}

func (x *GteUserOperationCommonHistoryRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *GteUserOperationCommonHistoryRequest) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *GteUserOperationCommonHistoryRequest) GetEndTimestamp() int64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

func (x *GteUserOperationCommonHistoryRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GteUserOperationCommonHistoryRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GteUserOperationCommonHistoryRequest) GetInstrumentAddress() string {
	if x != nil && x.InstrumentAddress != nil {
		return *x.InstrumentAddress
	}
	return ""
}

func (x *GteUserOperationCommonHistoryRequest) GetExpiry() uint32 {
	if x != nil && x.Expiry != nil {
		return *x.Expiry
	}
	return 0
}

type GetUserInstrumentTransferHistoryResponse struct {
	state         protoimpl.MessageState                             `protogen:"open.v1"`
	List          []*GetUserInstrumentTransferHistoryResponseDetails `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	TotalCount    uint32                                             `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserInstrumentTransferHistoryResponse) Reset() {
	*x = GetUserInstrumentTransferHistoryResponse{}
	mi := &file_indexer_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInstrumentTransferHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInstrumentTransferHistoryResponse) ProtoMessage() {}

func (x *GetUserInstrumentTransferHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInstrumentTransferHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetUserInstrumentTransferHistoryResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{9}
}

func (x *GetUserInstrumentTransferHistoryResponse) GetList() []*GetUserInstrumentTransferHistoryResponseDetails {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetUserInstrumentTransferHistoryResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetUserInstrumentTransferHistoryResponseDetails struct {
	state             protoimpl.MessageState               `protogen:"open.v1"`
	Id                string                               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InstrumentAddress string                               `protobuf:"bytes,2,opt,name=instrumentAddress,proto3" json:"instrumentAddress,omitempty"`
	Expiry            uint32                               `protobuf:"varint,3,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Value             string                               `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	ValueUsd          string                               `protobuf:"bytes,5,opt,name=valueUsd,proto3" json:"valueUsd,omitempty"`
	Timestamp         uint64                               `protobuf:"varint,6,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	TxHash            string                               `protobuf:"bytes,7,opt,name=txHash,proto3" json:"txHash,omitempty"`
	Type              GetUserInstrumentTransferHistoryType `protobuf:"varint,8,opt,name=type,proto3,enum=indexer.grpc.GetUserInstrumentTransferHistoryType" json:"type,omitempty"`
	Symbol            string                               `protobuf:"bytes,9,opt,name=symbol,proto3" json:"symbol,omitempty"`
	BaseToken         *TokenInfo                           `protobuf:"bytes,10,opt,name=baseToken,proto3" json:"baseToken,omitempty"`
	QuoteToken        *TokenInfo                           `protobuf:"bytes,11,opt,name=quoteToken,proto3" json:"quoteToken,omitempty"`
	TypeString        string                               `protobuf:"bytes,12,opt,name=typeString,proto3" json:"typeString,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetUserInstrumentTransferHistoryResponseDetails) Reset() {
	*x = GetUserInstrumentTransferHistoryResponseDetails{}
	mi := &file_indexer_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserInstrumentTransferHistoryResponseDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserInstrumentTransferHistoryResponseDetails) ProtoMessage() {}

func (x *GetUserInstrumentTransferHistoryResponseDetails) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserInstrumentTransferHistoryResponseDetails.ProtoReflect.Descriptor instead.
func (*GetUserInstrumentTransferHistoryResponseDetails) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserInstrumentTransferHistoryResponseDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetUserInstrumentTransferHistoryResponseDetails) GetInstrumentAddress() string {
	if x != nil {
		return x.InstrumentAddress
	}
	return ""
}

func (x *GetUserInstrumentTransferHistoryResponseDetails) GetExpiry() uint32 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *GetUserInstrumentTransferHistoryResponseDetails) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetUserInstrumentTransferHistoryResponseDetails) GetValueUsd() string {
	if x != nil {
		return x.ValueUsd
	}
	return ""
}

func (x *GetUserInstrumentTransferHistoryResponseDetails) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetUserInstrumentTransferHistoryResponseDetails) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *GetUserInstrumentTransferHistoryResponseDetails) GetType() GetUserInstrumentTransferHistoryType {
	if x != nil {
		return x.Type
	}
	return GetUserInstrumentTransferHistoryType_SCATTER
}

func (x *GetUserInstrumentTransferHistoryResponseDetails) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *GetUserInstrumentTransferHistoryResponseDetails) GetBaseToken() *TokenInfo {
	if x != nil {
		return x.BaseToken
	}
	return nil
}

func (x *GetUserInstrumentTransferHistoryResponseDetails) GetQuoteToken() *TokenInfo {
	if x != nil {
		return x.QuoteToken
	}
	return nil
}

func (x *GetUserInstrumentTransferHistoryResponseDetails) GetTypeString() string {
	if x != nil {
		return x.TypeString
	}
	return ""
}

type GetTradeVolumeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserAddress   string                 `protobuf:"bytes,1,opt,name=userAddress,proto3" json:"userAddress,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTradeVolumeRequest) Reset() {
	*x = GetTradeVolumeRequest{}
	mi := &file_indexer_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradeVolumeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeVolumeRequest) ProtoMessage() {}

func (x *GetTradeVolumeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeVolumeRequest.ProtoReflect.Descriptor instead.
func (*GetTradeVolumeRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{11}
}

func (x *GetTradeVolumeRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

type GetTradeVolumeResponse struct {
	state          protoimpl.MessageState           `protogen:"open.v1"`
	TotalVolumeUsd string                           `protobuf:"bytes,1,opt,name=totalVolumeUsd,proto3" json:"totalVolumeUsd,omitempty"`
	Details        []*GetTradeVolumeResponseDetails `protobuf:"bytes,2,rep,name=details,proto3" json:"details,omitempty"`
	UserAddress    string                           `protobuf:"bytes,3,opt,name=userAddress,proto3" json:"userAddress,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetTradeVolumeResponse) Reset() {
	*x = GetTradeVolumeResponse{}
	mi := &file_indexer_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradeVolumeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeVolumeResponse) ProtoMessage() {}

func (x *GetTradeVolumeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeVolumeResponse.ProtoReflect.Descriptor instead.
func (*GetTradeVolumeResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{12}
}

func (x *GetTradeVolumeResponse) GetTotalVolumeUsd() string {
	if x != nil {
		return x.TotalVolumeUsd
	}
	return ""
}

func (x *GetTradeVolumeResponse) GetDetails() []*GetTradeVolumeResponseDetails {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *GetTradeVolumeResponse) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

type GetTradeVolumeResponseDetails struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	InstrumentAddress string                 `protobuf:"bytes,1,opt,name=instrumentAddress,proto3" json:"instrumentAddress,omitempty"`
	Expiry            uint32                 `protobuf:"varint,2,opt,name=expiry,proto3" json:"expiry,omitempty"`
	QuoteAddress      string                 `protobuf:"bytes,3,opt,name=quoteAddress,proto3" json:"quoteAddress,omitempty"`
	VolumeUsd         string                 `protobuf:"bytes,4,opt,name=volumeUsd,proto3" json:"volumeUsd,omitempty"`
	QuoteVolume       string                 `protobuf:"bytes,5,opt,name=quoteVolume,proto3" json:"quoteVolume,omitempty"`
	BaseToken         *TokenInfo             `protobuf:"bytes,6,opt,name=baseToken,proto3" json:"baseToken,omitempty"`
	QuoteToken        *TokenInfo             `protobuf:"bytes,7,opt,name=quoteToken,proto3" json:"quoteToken,omitempty"`
	Symbol            string                 `protobuf:"bytes,8,opt,name=symbol,proto3" json:"symbol,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetTradeVolumeResponseDetails) Reset() {
	*x = GetTradeVolumeResponseDetails{}
	mi := &file_indexer_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTradeVolumeResponseDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTradeVolumeResponseDetails) ProtoMessage() {}

func (x *GetTradeVolumeResponseDetails) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTradeVolumeResponseDetails.ProtoReflect.Descriptor instead.
func (*GetTradeVolumeResponseDetails) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{13}
}

func (x *GetTradeVolumeResponseDetails) GetInstrumentAddress() string {
	if x != nil {
		return x.InstrumentAddress
	}
	return ""
}

func (x *GetTradeVolumeResponseDetails) GetExpiry() uint32 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *GetTradeVolumeResponseDetails) GetQuoteAddress() string {
	if x != nil {
		return x.QuoteAddress
	}
	return ""
}

func (x *GetTradeVolumeResponseDetails) GetVolumeUsd() string {
	if x != nil {
		return x.VolumeUsd
	}
	return ""
}

func (x *GetTradeVolumeResponseDetails) GetQuoteVolume() string {
	if x != nil {
		return x.QuoteVolume
	}
	return ""
}

func (x *GetTradeVolumeResponseDetails) GetBaseToken() *TokenInfo {
	if x != nil {
		return x.BaseToken
	}
	return nil
}

func (x *GetTradeVolumeResponseDetails) GetQuoteToken() *TokenInfo {
	if x != nil {
		return x.QuoteToken
	}
	return nil
}

func (x *GetTradeVolumeResponseDetails) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

type GteDepositWithdrawHistoryRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserAddress    string                 `protobuf:"bytes,1,opt,name=userAddress,proto3" json:"userAddress,omitempty"`
	StartTimestamp int64                  `protobuf:"varint,2,opt,name=startTimestamp,proto3" json:"startTimestamp,omitempty"`
	EndTimestamp   int64                  `protobuf:"varint,3,opt,name=endTimestamp,proto3" json:"endTimestamp,omitempty"`
	Size           uint32                 `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	Page           uint32                 `protobuf:"varint,5,opt,name=page,proto3" json:"page,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GteDepositWithdrawHistoryRequest) Reset() {
	*x = GteDepositWithdrawHistoryRequest{}
	mi := &file_indexer_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GteDepositWithdrawHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GteDepositWithdrawHistoryRequest) ProtoMessage() {}

func (x *GteDepositWithdrawHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GteDepositWithdrawHistoryRequest.ProtoReflect.Descriptor instead.
func (*GteDepositWithdrawHistoryRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{14}
}

func (x *GteDepositWithdrawHistoryRequest) GetUserAddress() string {
	if x != nil {
		return x.UserAddress
	}
	return ""
}

func (x *GteDepositWithdrawHistoryRequest) GetStartTimestamp() int64 {
	if x != nil {
		return x.StartTimestamp
	}
	return 0
}

func (x *GteDepositWithdrawHistoryRequest) GetEndTimestamp() int64 {
	if x != nil {
		return x.EndTimestamp
	}
	return 0
}

func (x *GteDepositWithdrawHistoryRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *GteDepositWithdrawHistoryRequest) GetPage() uint32 {
	if x != nil {
		return x.Page
	}
	return 0
}

type GetDepositWithdrawHistoryResponse struct {
	state         protoimpl.MessageState                      `protogen:"open.v1"`
	List          []*GetDepositWithdrawHistoryResponseDetails `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	TotalCount    uint32                                      `protobuf:"varint,2,opt,name=totalCount,proto3" json:"totalCount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositWithdrawHistoryResponse) Reset() {
	*x = GetDepositWithdrawHistoryResponse{}
	mi := &file_indexer_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositWithdrawHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositWithdrawHistoryResponse) ProtoMessage() {}

func (x *GetDepositWithdrawHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositWithdrawHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetDepositWithdrawHistoryResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{15}
}

func (x *GetDepositWithdrawHistoryResponse) GetList() []*GetDepositWithdrawHistoryResponseDetails {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *GetDepositWithdrawHistoryResponse) GetTotalCount() uint32 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetDepositWithdrawHistoryResponseDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TokenAddress  string                 `protobuf:"bytes,2,opt,name=tokenAddress,proto3" json:"tokenAddress,omitempty"`
	Timestamp     uint64                 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	ValueUsd      string                 `protobuf:"bytes,5,opt,name=valueUsd,proto3" json:"valueUsd,omitempty"`
	TxHash        string                 `protobuf:"bytes,6,opt,name=txHash,proto3" json:"txHash,omitempty"`
	Type          DepositWithdrawType    `protobuf:"varint,7,opt,name=type,proto3,enum=indexer.grpc.DepositWithdrawType" json:"type,omitempty"`
	TokenInfo     *TokenInfo             `protobuf:"bytes,8,opt,name=tokenInfo,proto3" json:"tokenInfo,omitempty"`
	TypeString    string                 `protobuf:"bytes,9,opt,name=typeString,proto3" json:"typeString,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDepositWithdrawHistoryResponseDetails) Reset() {
	*x = GetDepositWithdrawHistoryResponseDetails{}
	mi := &file_indexer_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDepositWithdrawHistoryResponseDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDepositWithdrawHistoryResponseDetails) ProtoMessage() {}

func (x *GetDepositWithdrawHistoryResponseDetails) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDepositWithdrawHistoryResponseDetails.ProtoReflect.Descriptor instead.
func (*GetDepositWithdrawHistoryResponseDetails) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{16}
}

func (x *GetDepositWithdrawHistoryResponseDetails) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetDepositWithdrawHistoryResponseDetails) GetTokenAddress() string {
	if x != nil {
		return x.TokenAddress
	}
	return ""
}

func (x *GetDepositWithdrawHistoryResponseDetails) GetTimestamp() uint64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetDepositWithdrawHistoryResponseDetails) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *GetDepositWithdrawHistoryResponseDetails) GetValueUsd() string {
	if x != nil {
		return x.ValueUsd
	}
	return ""
}

func (x *GetDepositWithdrawHistoryResponseDetails) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *GetDepositWithdrawHistoryResponseDetails) GetType() DepositWithdrawType {
	if x != nil {
		return x.Type
	}
	return DepositWithdrawType_DEPOSIT
}

func (x *GetDepositWithdrawHistoryResponseDetails) GetTokenInfo() *TokenInfo {
	if x != nil {
		return x.TokenInfo
	}
	return nil
}

func (x *GetDepositWithdrawHistoryResponseDetails) GetTypeString() string {
	if x != nil {
		return x.TypeString
	}
	return ""
}

type TokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Symbol        string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Decimals      uint64                 `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_indexer_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{17}
}

func (x *TokenInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TokenInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TokenInfo) GetDecimals() uint64 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *TokenInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

var File_indexer_proto protoreflect.FileDescriptor

const file_indexer_proto_rawDesc = "" +
	"\n" +
	"\rindexer.proto\x12\findexer.grpc\"\x83\x01\n" +
	"\x1bGetUserTradeHistoryResponse\x12D\n" +
	"\x04list\x18\x01 \x03(\v20.indexer.grpc.GetUserTradeHistoryResponseDetailsR\x04list\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x02 \x01(\rR\n" +
	"totalCount\"\xa6\x04\n" +
	"\"GetUserTradeHistoryResponseDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x11instrumentAddress\x18\x02 \x01(\tR\x11instrumentAddress\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\rR\x06expiry\x12\x12\n" +
	"\x04size\x18\x04 \x01(\tR\x04size\x12\x18\n" +
	"\abalance\x18\x05 \x01(\tR\abalance\x12\x14\n" +
	"\x05price\x18\x06 \x01(\tR\x05price\x12\x1a\n" +
	"\btradeFee\x18\a \x01(\tR\btradeFee\x12 \n" +
	"\vprotocolFee\x18\b \x01(\tR\vprotocolFee\x12\x1c\n" +
	"\ttimestamp\x18\t \x01(\x04R\ttimestamp\x12\x16\n" +
	"\x06txHash\x18\n" +
	" \x01(\tR\x06txHash\x126\n" +
	"\x04type\x18\v \x01(\x0e2\".indexer.grpc.UserTradeHistoryTypeR\x04type\x12\x16\n" +
	"\x06symbol\x18\f \x01(\tR\x06symbol\x125\n" +
	"\tbaseToken\x18\r \x01(\v2\x17.indexer.grpc.TokenInfoR\tbaseToken\x127\n" +
	"\n" +
	"quoteToken\x18\x0e \x01(\v2\x17.indexer.grpc.TokenInfoR\n" +
	"quoteToken\x12\x1e\n" +
	"\n" +
	"typeString\x18\x0f \x01(\tR\n" +
	"typeString\x12\x12\n" +
	"\x04side\x18\x10 \x01(\tR\x04side\"\x83\x01\n" +
	"\x1bGetUserOrderHistoryResponse\x12D\n" +
	"\x04list\x18\x01 \x03(\v20.indexer.grpc.GetUserOrderHistoryResponseDetailsR\x04list\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x02 \x01(\rR\n" +
	"totalCount\"\xfc\x05\n" +
	"\"GetUserOrderHistoryResponseDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x11instrumentAddress\x18\x02 \x01(\tR\x11instrumentAddress\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\rR\x06expiry\x12&\n" +
	"\x0eplaceTimestamp\x18\x04 \x01(\x04R\x0eplaceTimestamp\x12 \n" +
	"\vplaceTxHash\x18\x05 \x01(\tR\vplaceTxHash\x12\x12\n" +
	"\x04size\x18\a \x01(\tR\x04size\x12\x18\n" +
	"\abalance\x18\b \x01(\tR\abalance\x12\x1c\n" +
	"\ttakenSize\x18\t \x01(\tR\ttakenSize\x12\"\n" +
	"\ftakenBalance\x18\n" +
	" \x01(\tR\ftakenBalance\x12\x1e\n" +
	"\n" +
	"orderPrice\x18\v \x01(\tR\n" +
	"orderPrice\x12\x1c\n" +
	"\tfeeRebate\x18\f \x01(\tR\tfeeRebate\x128\n" +
	"\x04type\x18\x06 \x01(\x0e2$.indexer.grpc.UserOrderHistoryStatusR\x04type\x12(\n" +
	"\x0fcancelTimestamp\x18\r \x01(\x04R\x0fcancelTimestamp\x12\"\n" +
	"\fcancelTxHash\x18\x0e \x01(\tR\fcancelTxHash\x12$\n" +
	"\rfillTimestamp\x18\x0f \x01(\x04R\rfillTimestamp\x12\x1e\n" +
	"\n" +
	"fillTxHash\x18\x10 \x01(\tR\n" +
	"fillTxHash\x12\x16\n" +
	"\x06symbol\x18\x11 \x01(\tR\x06symbol\x125\n" +
	"\tbaseToken\x18\x12 \x01(\v2\x17.indexer.grpc.TokenInfoR\tbaseToken\x127\n" +
	"\n" +
	"quoteToken\x18\x13 \x01(\v2\x17.indexer.grpc.TokenInfoR\n" +
	"quoteToken\x12\x1e\n" +
	"\n" +
	"typeString\x18\x14 \x01(\tR\n" +
	"typeString\x12\x12\n" +
	"\x04side\x18\x15 \x01(\tR\x04side\"\x8b\x01\n" +
	"\x1fGetUserLiquidityHistoryResponse\x12H\n" +
	"\x04list\x18\x01 \x03(\v24.indexer.grpc.GetUserLiquidityHistoryResponseDetailsR\x04list\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x02 \x01(\rR\n" +
	"totalCount\"\xe8\x04\n" +
	"&GetUserLiquidityHistoryResponseDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x11instrumentAddress\x18\x02 \x01(\tR\x11instrumentAddress\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\rR\x06expiry\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x04R\ttimestamp\x12\x16\n" +
	"\x06txHash\x18\x05 \x01(\tR\x06txHash\x12:\n" +
	"\x04type\x18\x06 \x01(\x0e2&.indexer.grpc.UserLiquidityHistoryTypeR\x04type\x12\x1c\n" +
	"\tlowerTick\x18\a \x01(\x03R\tlowerTick\x12\x1c\n" +
	"\tupperTick\x18\b \x01(\x03R\tupperTick\x12\x1e\n" +
	"\n" +
	"lowerPrice\x18\t \x01(\tR\n" +
	"lowerPrice\x12\x1e\n" +
	"\n" +
	"upperPrice\x18\n" +
	" \x01(\tR\n" +
	"upperPrice\x12\x1c\n" +
	"\tfairPrice\x18\v \x01(\tR\tfairPrice\x12\x16\n" +
	"\x06amount\x18\f \x01(\tR\x06amount\x12\x1c\n" +
	"\tfeeEarned\x18\r \x01(\tR\tfeeEarned\x12\x16\n" +
	"\x06symbol\x18\x0e \x01(\tR\x06symbol\x125\n" +
	"\tbaseToken\x18\x0f \x01(\v2\x17.indexer.grpc.TokenInfoR\tbaseToken\x127\n" +
	"\n" +
	"quoteToken\x18\x10 \x01(\v2\x17.indexer.grpc.TokenInfoR\n" +
	"quoteToken\x12\x1e\n" +
	"\n" +
	"typeString\x18\x11 \x01(\tR\n" +
	"typeString\"\x87\x01\n" +
	"\x1dGetUserFundingHistoryResponse\x12F\n" +
	"\x04list\x18\x01 \x03(\v22.indexer.grpc.GetUserFundingHistoryResponseDetailsR\x04list\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x02 \x01(\rR\n" +
	"totalCount\"\xc2\x03\n" +
	"$GetUserFundingHistoryResponseDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x11instrumentAddress\x18\x02 \x01(\tR\x11instrumentAddress\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\rR\x06expiry\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1a\n" +
	"\bvalueUsd\x18\x05 \x01(\tR\bvalueUsd\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\x12\x16\n" +
	"\x06txHash\x18\a \x01(\tR\x06txHash\x124\n" +
	"\x04type\x18\b \x01(\x0e2 .indexer.grpc.GetUserFundingTypeR\x04type\x12\x16\n" +
	"\x06symbol\x18\t \x01(\tR\x06symbol\x125\n" +
	"\tbaseToken\x18\n" +
	" \x01(\v2\x17.indexer.grpc.TokenInfoR\tbaseToken\x127\n" +
	"\n" +
	"quoteToken\x18\v \x01(\v2\x17.indexer.grpc.TokenInfoR\n" +
	"quoteToken\x12\x1e\n" +
	"\n" +
	"typeString\x18\f \x01(\tR\n" +
	"typeString\"\xad\x02\n" +
	"$GteUserOperationCommonHistoryRequest\x12 \n" +
	"\vuserAddress\x18\x01 \x01(\tR\vuserAddress\x12&\n" +
	"\x0estartTimestamp\x18\x02 \x01(\x03R\x0estartTimestamp\x12\"\n" +
	"\fendTimestamp\x18\x03 \x01(\x03R\fendTimestamp\x12\x12\n" +
	"\x04page\x18\x04 \x01(\rR\x04page\x12\x12\n" +
	"\x04size\x18\x05 \x01(\rR\x04size\x121\n" +
	"\x11instrumentAddress\x18\x06 \x01(\tH\x00R\x11instrumentAddress\x88\x01\x01\x12\x1b\n" +
	"\x06expiry\x18\a \x01(\rH\x01R\x06expiry\x88\x01\x01B\x14\n" +
	"\x12_instrumentAddressB\t\n" +
	"\a_expiry\"\x9d\x01\n" +
	"(GetUserInstrumentTransferHistoryResponse\x12Q\n" +
	"\x04list\x18\x01 \x03(\v2=.indexer.grpc.GetUserInstrumentTransferHistoryResponseDetailsR\x04list\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x02 \x01(\rR\n" +
	"totalCount\"\xdf\x03\n" +
	"/GetUserInstrumentTransferHistoryResponseDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12,\n" +
	"\x11instrumentAddress\x18\x02 \x01(\tR\x11instrumentAddress\x12\x16\n" +
	"\x06expiry\x18\x03 \x01(\rR\x06expiry\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1a\n" +
	"\bvalueUsd\x18\x05 \x01(\tR\bvalueUsd\x12\x1c\n" +
	"\ttimestamp\x18\x06 \x01(\x04R\ttimestamp\x12\x16\n" +
	"\x06txHash\x18\a \x01(\tR\x06txHash\x12F\n" +
	"\x04type\x18\b \x01(\x0e22.indexer.grpc.GetUserInstrumentTransferHistoryTypeR\x04type\x12\x16\n" +
	"\x06symbol\x18\t \x01(\tR\x06symbol\x125\n" +
	"\tbaseToken\x18\n" +
	" \x01(\v2\x17.indexer.grpc.TokenInfoR\tbaseToken\x127\n" +
	"\n" +
	"quoteToken\x18\v \x01(\v2\x17.indexer.grpc.TokenInfoR\n" +
	"quoteToken\x12\x1e\n" +
	"\n" +
	"typeString\x18\f \x01(\tR\n" +
	"typeString\"9\n" +
	"\x15GetTradeVolumeRequest\x12 \n" +
	"\vuserAddress\x18\x01 \x01(\tR\vuserAddress\"\xa9\x01\n" +
	"\x16GetTradeVolumeResponse\x12&\n" +
	"\x0etotalVolumeUsd\x18\x01 \x01(\tR\x0etotalVolumeUsd\x12E\n" +
	"\adetails\x18\x02 \x03(\v2+.indexer.grpc.GetTradeVolumeResponseDetailsR\adetails\x12 \n" +
	"\vuserAddress\x18\x03 \x01(\tR\vuserAddress\"\xd1\x02\n" +
	"\x1dGetTradeVolumeResponseDetails\x12,\n" +
	"\x11instrumentAddress\x18\x01 \x01(\tR\x11instrumentAddress\x12\x16\n" +
	"\x06expiry\x18\x02 \x01(\rR\x06expiry\x12\"\n" +
	"\fquoteAddress\x18\x03 \x01(\tR\fquoteAddress\x12\x1c\n" +
	"\tvolumeUsd\x18\x04 \x01(\tR\tvolumeUsd\x12 \n" +
	"\vquoteVolume\x18\x05 \x01(\tR\vquoteVolume\x125\n" +
	"\tbaseToken\x18\x06 \x01(\v2\x17.indexer.grpc.TokenInfoR\tbaseToken\x127\n" +
	"\n" +
	"quoteToken\x18\a \x01(\v2\x17.indexer.grpc.TokenInfoR\n" +
	"quoteToken\x12\x16\n" +
	"\x06symbol\x18\b \x01(\tR\x06symbol\"\xb8\x01\n" +
	" GteDepositWithdrawHistoryRequest\x12 \n" +
	"\vuserAddress\x18\x01 \x01(\tR\vuserAddress\x12&\n" +
	"\x0estartTimestamp\x18\x02 \x01(\x03R\x0estartTimestamp\x12\"\n" +
	"\fendTimestamp\x18\x03 \x01(\x03R\fendTimestamp\x12\x12\n" +
	"\x04size\x18\x04 \x01(\rR\x04size\x12\x12\n" +
	"\x04page\x18\x05 \x01(\rR\x04page\"\x8f\x01\n" +
	"!GetDepositWithdrawHistoryResponse\x12J\n" +
	"\x04list\x18\x01 \x03(\v26.indexer.grpc.GetDepositWithdrawHistoryResponseDetailsR\x04list\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x02 \x01(\rR\n" +
	"totalCount\"\xd4\x02\n" +
	"(GetDepositWithdrawHistoryResponseDetails\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\"\n" +
	"\ftokenAddress\x18\x02 \x01(\tR\ftokenAddress\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x04R\ttimestamp\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1a\n" +
	"\bvalueUsd\x18\x05 \x01(\tR\bvalueUsd\x12\x16\n" +
	"\x06txHash\x18\x06 \x01(\tR\x06txHash\x125\n" +
	"\x04type\x18\a \x01(\x0e2!.indexer.grpc.DepositWithdrawTypeR\x04type\x125\n" +
	"\ttokenInfo\x18\b \x01(\v2\x17.indexer.grpc.TokenInfoR\ttokenInfo\x12\x1e\n" +
	"\n" +
	"typeString\x18\t \x01(\tR\n" +
	"typeString\"o\n" +
	"\tTokenInfo\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bdecimals\x18\x03 \x01(\x04R\bdecimals\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image*Z\n" +
	"\x14UserTradeHistoryType\x12\x0e\n" +
	"\n" +
	"FILL_TRADE\x10\x00\x12\x0f\n" +
	"\vLIMIT_TRADE\x10\x01\x12\x10\n" +
	"\fMARKET_TRADE\x10\x02\x12\x0f\n" +
	"\vSWEEP_TRADE\x10\x03*>\n" +
	"\x16UserOrderHistoryStatus\x12\x12\n" +
	"\x0eCANCELED_ORDER\x10\x00\x12\x10\n" +
	"\fFILLED_ORDER\x10\x01*C\n" +
	"\x18UserLiquidityHistoryType\x12\x11\n" +
	"\rADD_LIQUIDITY\x10\x00\x12\x14\n" +
	"\x10REMOVE_LIQUIDITY\x10\x01*<\n" +
	"\x12GetUserFundingType\x12\x10\n" +
	"\fFUNDING_PAID\x10\x00\x12\x14\n" +
	"\x10FUNDING_RECEIVED\x10\x01*?\n" +
	"$GetUserInstrumentTransferHistoryType\x12\v\n" +
	"\aSCATTER\x10\x00\x12\n" +
	"\n" +
	"\x06GATHER\x10\x01*0\n" +
	"\x13DepositWithdrawType\x12\v\n" +
	"\aDEPOSIT\x10\x00\x12\f\n" +
	"\bWITHDRAW\x10\x012\xe0\x06\n" +
	"\x0eIndexerService\x12[\n" +
	"\x0eGetTradeVolume\x12#.indexer.grpc.GetTradeVolumeRequest\x1a$.indexer.grpc.GetTradeVolumeResponse\x12|\n" +
	"\x19GetDepositWithdrawHistory\x12..indexer.grpc.GteDepositWithdrawHistoryRequest\x1a/.indexer.grpc.GetDepositWithdrawHistoryResponse\x12\x8e\x01\n" +
	" GetUserInstrumentTransferHistory\x122.indexer.grpc.GteUserOperationCommonHistoryRequest\x1a6.indexer.grpc.GetUserInstrumentTransferHistoryResponse\x12x\n" +
	"\x15GetUserFundingHistory\x122.indexer.grpc.GteUserOperationCommonHistoryRequest\x1a+.indexer.grpc.GetUserFundingHistoryResponse\x12|\n" +
	"\x17GetUserLiquidityHistory\x122.indexer.grpc.GteUserOperationCommonHistoryRequest\x1a-.indexer.grpc.GetUserLiquidityHistoryResponse\x12t\n" +
	"\x13GetUserOrderHistory\x122.indexer.grpc.GteUserOperationCommonHistoryRequest\x1a).indexer.grpc.GetUserOrderHistoryResponse\x12t\n" +
	"\x13GetUserTradeHistory\x122.indexer.grpc.GteUserOperationCommonHistoryRequest\x1a).indexer.grpc.GetUserTradeHistoryResponseB\x19Z\x17../;indexer_grpc_clientb\x06proto3"

var (
	file_indexer_proto_rawDescOnce sync.Once
	file_indexer_proto_rawDescData []byte
)

func file_indexer_proto_rawDescGZIP() []byte {
	file_indexer_proto_rawDescOnce.Do(func() {
		file_indexer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indexer_proto_rawDesc), len(file_indexer_proto_rawDesc)))
	})
	return file_indexer_proto_rawDescData
}

var file_indexer_proto_enumTypes = make([]protoimpl.EnumInfo, 6)
var file_indexer_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_indexer_proto_goTypes = []any{
	(UserTradeHistoryType)(0),                               // 0: indexer.grpc.UserTradeHistoryType
	(UserOrderHistoryStatus)(0),                             // 1: indexer.grpc.UserOrderHistoryStatus
	(UserLiquidityHistoryType)(0),                           // 2: indexer.grpc.UserLiquidityHistoryType
	(GetUserFundingType)(0),                                 // 3: indexer.grpc.GetUserFundingType
	(GetUserInstrumentTransferHistoryType)(0),               // 4: indexer.grpc.GetUserInstrumentTransferHistoryType
	(DepositWithdrawType)(0),                                // 5: indexer.grpc.DepositWithdrawType
	(*GetUserTradeHistoryResponse)(nil),                     // 6: indexer.grpc.GetUserTradeHistoryResponse
	(*GetUserTradeHistoryResponseDetails)(nil),              // 7: indexer.grpc.GetUserTradeHistoryResponseDetails
	(*GetUserOrderHistoryResponse)(nil),                     // 8: indexer.grpc.GetUserOrderHistoryResponse
	(*GetUserOrderHistoryResponseDetails)(nil),              // 9: indexer.grpc.GetUserOrderHistoryResponseDetails
	(*GetUserLiquidityHistoryResponse)(nil),                 // 10: indexer.grpc.GetUserLiquidityHistoryResponse
	(*GetUserLiquidityHistoryResponseDetails)(nil),          // 11: indexer.grpc.GetUserLiquidityHistoryResponseDetails
	(*GetUserFundingHistoryResponse)(nil),                   // 12: indexer.grpc.GetUserFundingHistoryResponse
	(*GetUserFundingHistoryResponseDetails)(nil),            // 13: indexer.grpc.GetUserFundingHistoryResponseDetails
	(*GteUserOperationCommonHistoryRequest)(nil),            // 14: indexer.grpc.GteUserOperationCommonHistoryRequest
	(*GetUserInstrumentTransferHistoryResponse)(nil),        // 15: indexer.grpc.GetUserInstrumentTransferHistoryResponse
	(*GetUserInstrumentTransferHistoryResponseDetails)(nil), // 16: indexer.grpc.GetUserInstrumentTransferHistoryResponseDetails
	(*GetTradeVolumeRequest)(nil),                           // 17: indexer.grpc.GetTradeVolumeRequest
	(*GetTradeVolumeResponse)(nil),                          // 18: indexer.grpc.GetTradeVolumeResponse
	(*GetTradeVolumeResponseDetails)(nil),                   // 19: indexer.grpc.GetTradeVolumeResponseDetails
	(*GteDepositWithdrawHistoryRequest)(nil),                // 20: indexer.grpc.GteDepositWithdrawHistoryRequest
	(*GetDepositWithdrawHistoryResponse)(nil),               // 21: indexer.grpc.GetDepositWithdrawHistoryResponse
	(*GetDepositWithdrawHistoryResponseDetails)(nil),        // 22: indexer.grpc.GetDepositWithdrawHistoryResponseDetails
	(*TokenInfo)(nil),                                       // 23: indexer.grpc.TokenInfo
}
var file_indexer_proto_depIdxs = []int32{
	7,  // 0: indexer.grpc.GetUserTradeHistoryResponse.list:type_name -> indexer.grpc.GetUserTradeHistoryResponseDetails
	0,  // 1: indexer.grpc.GetUserTradeHistoryResponseDetails.type:type_name -> indexer.grpc.UserTradeHistoryType
	23, // 2: indexer.grpc.GetUserTradeHistoryResponseDetails.baseToken:type_name -> indexer.grpc.TokenInfo
	23, // 3: indexer.grpc.GetUserTradeHistoryResponseDetails.quoteToken:type_name -> indexer.grpc.TokenInfo
	9,  // 4: indexer.grpc.GetUserOrderHistoryResponse.list:type_name -> indexer.grpc.GetUserOrderHistoryResponseDetails
	1,  // 5: indexer.grpc.GetUserOrderHistoryResponseDetails.type:type_name -> indexer.grpc.UserOrderHistoryStatus
	23, // 6: indexer.grpc.GetUserOrderHistoryResponseDetails.baseToken:type_name -> indexer.grpc.TokenInfo
	23, // 7: indexer.grpc.GetUserOrderHistoryResponseDetails.quoteToken:type_name -> indexer.grpc.TokenInfo
	11, // 8: indexer.grpc.GetUserLiquidityHistoryResponse.list:type_name -> indexer.grpc.GetUserLiquidityHistoryResponseDetails
	2,  // 9: indexer.grpc.GetUserLiquidityHistoryResponseDetails.type:type_name -> indexer.grpc.UserLiquidityHistoryType
	23, // 10: indexer.grpc.GetUserLiquidityHistoryResponseDetails.baseToken:type_name -> indexer.grpc.TokenInfo
	23, // 11: indexer.grpc.GetUserLiquidityHistoryResponseDetails.quoteToken:type_name -> indexer.grpc.TokenInfo
	13, // 12: indexer.grpc.GetUserFundingHistoryResponse.list:type_name -> indexer.grpc.GetUserFundingHistoryResponseDetails
	3,  // 13: indexer.grpc.GetUserFundingHistoryResponseDetails.type:type_name -> indexer.grpc.GetUserFundingType
	23, // 14: indexer.grpc.GetUserFundingHistoryResponseDetails.baseToken:type_name -> indexer.grpc.TokenInfo
	23, // 15: indexer.grpc.GetUserFundingHistoryResponseDetails.quoteToken:type_name -> indexer.grpc.TokenInfo
	16, // 16: indexer.grpc.GetUserInstrumentTransferHistoryResponse.list:type_name -> indexer.grpc.GetUserInstrumentTransferHistoryResponseDetails
	4,  // 17: indexer.grpc.GetUserInstrumentTransferHistoryResponseDetails.type:type_name -> indexer.grpc.GetUserInstrumentTransferHistoryType
	23, // 18: indexer.grpc.GetUserInstrumentTransferHistoryResponseDetails.baseToken:type_name -> indexer.grpc.TokenInfo
	23, // 19: indexer.grpc.GetUserInstrumentTransferHistoryResponseDetails.quoteToken:type_name -> indexer.grpc.TokenInfo
	19, // 20: indexer.grpc.GetTradeVolumeResponse.details:type_name -> indexer.grpc.GetTradeVolumeResponseDetails
	23, // 21: indexer.grpc.GetTradeVolumeResponseDetails.baseToken:type_name -> indexer.grpc.TokenInfo
	23, // 22: indexer.grpc.GetTradeVolumeResponseDetails.quoteToken:type_name -> indexer.grpc.TokenInfo
	22, // 23: indexer.grpc.GetDepositWithdrawHistoryResponse.list:type_name -> indexer.grpc.GetDepositWithdrawHistoryResponseDetails
	5,  // 24: indexer.grpc.GetDepositWithdrawHistoryResponseDetails.type:type_name -> indexer.grpc.DepositWithdrawType
	23, // 25: indexer.grpc.GetDepositWithdrawHistoryResponseDetails.tokenInfo:type_name -> indexer.grpc.TokenInfo
	17, // 26: indexer.grpc.IndexerService.GetTradeVolume:input_type -> indexer.grpc.GetTradeVolumeRequest
	20, // 27: indexer.grpc.IndexerService.GetDepositWithdrawHistory:input_type -> indexer.grpc.GteDepositWithdrawHistoryRequest
	14, // 28: indexer.grpc.IndexerService.GetUserInstrumentTransferHistory:input_type -> indexer.grpc.GteUserOperationCommonHistoryRequest
	14, // 29: indexer.grpc.IndexerService.GetUserFundingHistory:input_type -> indexer.grpc.GteUserOperationCommonHistoryRequest
	14, // 30: indexer.grpc.IndexerService.GetUserLiquidityHistory:input_type -> indexer.grpc.GteUserOperationCommonHistoryRequest
	14, // 31: indexer.grpc.IndexerService.GetUserOrderHistory:input_type -> indexer.grpc.GteUserOperationCommonHistoryRequest
	14, // 32: indexer.grpc.IndexerService.GetUserTradeHistory:input_type -> indexer.grpc.GteUserOperationCommonHistoryRequest
	18, // 33: indexer.grpc.IndexerService.GetTradeVolume:output_type -> indexer.grpc.GetTradeVolumeResponse
	21, // 34: indexer.grpc.IndexerService.GetDepositWithdrawHistory:output_type -> indexer.grpc.GetDepositWithdrawHistoryResponse
	15, // 35: indexer.grpc.IndexerService.GetUserInstrumentTransferHistory:output_type -> indexer.grpc.GetUserInstrumentTransferHistoryResponse
	12, // 36: indexer.grpc.IndexerService.GetUserFundingHistory:output_type -> indexer.grpc.GetUserFundingHistoryResponse
	10, // 37: indexer.grpc.IndexerService.GetUserLiquidityHistory:output_type -> indexer.grpc.GetUserLiquidityHistoryResponse
	8,  // 38: indexer.grpc.IndexerService.GetUserOrderHistory:output_type -> indexer.grpc.GetUserOrderHistoryResponse
	6,  // 39: indexer.grpc.IndexerService.GetUserTradeHistory:output_type -> indexer.grpc.GetUserTradeHistoryResponse
	33, // [33:40] is the sub-list for method output_type
	26, // [26:33] is the sub-list for method input_type
	26, // [26:26] is the sub-list for extension type_name
	26, // [26:26] is the sub-list for extension extendee
	0,  // [0:26] is the sub-list for field type_name
}

func init() { file_indexer_proto_init() }
func file_indexer_proto_init() {
	if File_indexer_proto != nil {
		return
	}
	file_indexer_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indexer_proto_rawDesc), len(file_indexer_proto_rawDesc)),
			NumEnums:      6,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_indexer_proto_goTypes,
		DependencyIndexes: file_indexer_proto_depIdxs,
		EnumInfos:         file_indexer_proto_enumTypes,
		MessageInfos:      file_indexer_proto_msgTypes,
	}.Build()
	File_indexer_proto = out.File
	file_indexer_proto_goTypes = nil
	file_indexer_proto_depIdxs = nil
}
