// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: indexer.proto

package indexer_grpc_client

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IndexerService_GetTradeVolume_FullMethodName                   = "/indexer.grpc.IndexerService/GetTradeVolume"
	IndexerService_GetDepositWithdrawHistory_FullMethodName        = "/indexer.grpc.IndexerService/GetDepositWithdrawHistory"
	IndexerService_GetUserInstrumentTransferHistory_FullMethodName = "/indexer.grpc.IndexerService/GetUserInstrumentTransferHistory"
	IndexerService_GetUserFundingHistory_FullMethodName            = "/indexer.grpc.IndexerService/GetUserFundingHistory"
	IndexerService_GetUserLiquidityHistory_FullMethodName          = "/indexer.grpc.IndexerService/GetUserLiquidityHistory"
	IndexerService_GetUserOrderHistory_FullMethodName              = "/indexer.grpc.IndexerService/GetUserOrderHistory"
	IndexerService_GetUserTradeHistory_FullMethodName              = "/indexer.grpc.IndexerService/GetUserTradeHistory"
)

// IndexerServiceClient is the client API for IndexerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IndexerServiceClient interface {
	GetTradeVolume(ctx context.Context, in *GetTradeVolumeRequest, opts ...grpc.CallOption) (*GetTradeVolumeResponse, error)
	GetDepositWithdrawHistory(ctx context.Context, in *GteDepositWithdrawHistoryRequest, opts ...grpc.CallOption) (*GetDepositWithdrawHistoryResponse, error)
	GetUserInstrumentTransferHistory(ctx context.Context, in *GteUserOperationCommonHistoryRequest, opts ...grpc.CallOption) (*GetUserInstrumentTransferHistoryResponse, error)
	GetUserFundingHistory(ctx context.Context, in *GteUserOperationCommonHistoryRequest, opts ...grpc.CallOption) (*GetUserFundingHistoryResponse, error)
	GetUserLiquidityHistory(ctx context.Context, in *GteUserOperationCommonHistoryRequest, opts ...grpc.CallOption) (*GetUserLiquidityHistoryResponse, error)
	GetUserOrderHistory(ctx context.Context, in *GteUserOperationCommonHistoryRequest, opts ...grpc.CallOption) (*GetUserOrderHistoryResponse, error)
	GetUserTradeHistory(ctx context.Context, in *GteUserOperationCommonHistoryRequest, opts ...grpc.CallOption) (*GetUserTradeHistoryResponse, error)
}

type indexerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIndexerServiceClient(cc grpc.ClientConnInterface) IndexerServiceClient {
	return &indexerServiceClient{cc}
}

func (c *indexerServiceClient) GetTradeVolume(ctx context.Context, in *GetTradeVolumeRequest, opts ...grpc.CallOption) (*GetTradeVolumeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTradeVolumeResponse)
	err := c.cc.Invoke(ctx, IndexerService_GetTradeVolume_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexerServiceClient) GetDepositWithdrawHistory(ctx context.Context, in *GteDepositWithdrawHistoryRequest, opts ...grpc.CallOption) (*GetDepositWithdrawHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDepositWithdrawHistoryResponse)
	err := c.cc.Invoke(ctx, IndexerService_GetDepositWithdrawHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexerServiceClient) GetUserInstrumentTransferHistory(ctx context.Context, in *GteUserOperationCommonHistoryRequest, opts ...grpc.CallOption) (*GetUserInstrumentTransferHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserInstrumentTransferHistoryResponse)
	err := c.cc.Invoke(ctx, IndexerService_GetUserInstrumentTransferHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexerServiceClient) GetUserFundingHistory(ctx context.Context, in *GteUserOperationCommonHistoryRequest, opts ...grpc.CallOption) (*GetUserFundingHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserFundingHistoryResponse)
	err := c.cc.Invoke(ctx, IndexerService_GetUserFundingHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexerServiceClient) GetUserLiquidityHistory(ctx context.Context, in *GteUserOperationCommonHistoryRequest, opts ...grpc.CallOption) (*GetUserLiquidityHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserLiquidityHistoryResponse)
	err := c.cc.Invoke(ctx, IndexerService_GetUserLiquidityHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexerServiceClient) GetUserOrderHistory(ctx context.Context, in *GteUserOperationCommonHistoryRequest, opts ...grpc.CallOption) (*GetUserOrderHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserOrderHistoryResponse)
	err := c.cc.Invoke(ctx, IndexerService_GetUserOrderHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *indexerServiceClient) GetUserTradeHistory(ctx context.Context, in *GteUserOperationCommonHistoryRequest, opts ...grpc.CallOption) (*GetUserTradeHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUserTradeHistoryResponse)
	err := c.cc.Invoke(ctx, IndexerService_GetUserTradeHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IndexerServiceServer is the server API for IndexerService service.
// All implementations must embed UnimplementedIndexerServiceServer
// for forward compatibility.
type IndexerServiceServer interface {
	GetTradeVolume(context.Context, *GetTradeVolumeRequest) (*GetTradeVolumeResponse, error)
	GetDepositWithdrawHistory(context.Context, *GteDepositWithdrawHistoryRequest) (*GetDepositWithdrawHistoryResponse, error)
	GetUserInstrumentTransferHistory(context.Context, *GteUserOperationCommonHistoryRequest) (*GetUserInstrumentTransferHistoryResponse, error)
	GetUserFundingHistory(context.Context, *GteUserOperationCommonHistoryRequest) (*GetUserFundingHistoryResponse, error)
	GetUserLiquidityHistory(context.Context, *GteUserOperationCommonHistoryRequest) (*GetUserLiquidityHistoryResponse, error)
	GetUserOrderHistory(context.Context, *GteUserOperationCommonHistoryRequest) (*GetUserOrderHistoryResponse, error)
	GetUserTradeHistory(context.Context, *GteUserOperationCommonHistoryRequest) (*GetUserTradeHistoryResponse, error)
	mustEmbedUnimplementedIndexerServiceServer()
}

// UnimplementedIndexerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIndexerServiceServer struct{}

func (UnimplementedIndexerServiceServer) GetTradeVolume(context.Context, *GetTradeVolumeRequest) (*GetTradeVolumeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTradeVolume not implemented")
}
func (UnimplementedIndexerServiceServer) GetDepositWithdrawHistory(context.Context, *GteDepositWithdrawHistoryRequest) (*GetDepositWithdrawHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDepositWithdrawHistory not implemented")
}
func (UnimplementedIndexerServiceServer) GetUserInstrumentTransferHistory(context.Context, *GteUserOperationCommonHistoryRequest) (*GetUserInstrumentTransferHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserInstrumentTransferHistory not implemented")
}
func (UnimplementedIndexerServiceServer) GetUserFundingHistory(context.Context, *GteUserOperationCommonHistoryRequest) (*GetUserFundingHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserFundingHistory not implemented")
}
func (UnimplementedIndexerServiceServer) GetUserLiquidityHistory(context.Context, *GteUserOperationCommonHistoryRequest) (*GetUserLiquidityHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserLiquidityHistory not implemented")
}
func (UnimplementedIndexerServiceServer) GetUserOrderHistory(context.Context, *GteUserOperationCommonHistoryRequest) (*GetUserOrderHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserOrderHistory not implemented")
}
func (UnimplementedIndexerServiceServer) GetUserTradeHistory(context.Context, *GteUserOperationCommonHistoryRequest) (*GetUserTradeHistoryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUserTradeHistory not implemented")
}
func (UnimplementedIndexerServiceServer) mustEmbedUnimplementedIndexerServiceServer() {}
func (UnimplementedIndexerServiceServer) testEmbeddedByValue()                        {}

// UnsafeIndexerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IndexerServiceServer will
// result in compilation errors.
type UnsafeIndexerServiceServer interface {
	mustEmbedUnimplementedIndexerServiceServer()
}

func RegisterIndexerServiceServer(s grpc.ServiceRegistrar, srv IndexerServiceServer) {
	// If the following call pancis, it indicates UnimplementedIndexerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IndexerService_ServiceDesc, srv)
}

func _IndexerService_GetTradeVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTradeVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServiceServer).GetTradeVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexerService_GetTradeVolume_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServiceServer).GetTradeVolume(ctx, req.(*GetTradeVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexerService_GetDepositWithdrawHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GteDepositWithdrawHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServiceServer).GetDepositWithdrawHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexerService_GetDepositWithdrawHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServiceServer).GetDepositWithdrawHistory(ctx, req.(*GteDepositWithdrawHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexerService_GetUserInstrumentTransferHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GteUserOperationCommonHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServiceServer).GetUserInstrumentTransferHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexerService_GetUserInstrumentTransferHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServiceServer).GetUserInstrumentTransferHistory(ctx, req.(*GteUserOperationCommonHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexerService_GetUserFundingHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GteUserOperationCommonHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServiceServer).GetUserFundingHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexerService_GetUserFundingHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServiceServer).GetUserFundingHistory(ctx, req.(*GteUserOperationCommonHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexerService_GetUserLiquidityHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GteUserOperationCommonHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServiceServer).GetUserLiquidityHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexerService_GetUserLiquidityHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServiceServer).GetUserLiquidityHistory(ctx, req.(*GteUserOperationCommonHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexerService_GetUserOrderHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GteUserOperationCommonHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServiceServer).GetUserOrderHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexerService_GetUserOrderHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServiceServer).GetUserOrderHistory(ctx, req.(*GteUserOperationCommonHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IndexerService_GetUserTradeHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GteUserOperationCommonHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IndexerServiceServer).GetUserTradeHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IndexerService_GetUserTradeHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IndexerServiceServer).GetUserTradeHistory(ctx, req.(*GteUserOperationCommonHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IndexerService_ServiceDesc is the grpc.ServiceDesc for IndexerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IndexerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "indexer.grpc.IndexerService",
	HandlerType: (*IndexerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetTradeVolume",
			Handler:    _IndexerService_GetTradeVolume_Handler,
		},
		{
			MethodName: "GetDepositWithdrawHistory",
			Handler:    _IndexerService_GetDepositWithdrawHistory_Handler,
		},
		{
			MethodName: "GetUserInstrumentTransferHistory",
			Handler:    _IndexerService_GetUserInstrumentTransferHistory_Handler,
		},
		{
			MethodName: "GetUserFundingHistory",
			Handler:    _IndexerService_GetUserFundingHistory_Handler,
		},
		{
			MethodName: "GetUserLiquidityHistory",
			Handler:    _IndexerService_GetUserLiquidityHistory_Handler,
		},
		{
			MethodName: "GetUserOrderHistory",
			Handler:    _IndexerService_GetUserOrderHistory_Handler,
		},
		{
			MethodName: "GetUserTradeHistory",
			Handler:    _IndexerService_GetUserTradeHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "indexer.proto",
}
