// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/common/health": {
            "get": {
                "description": "HealthCheck",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Common"
                ],
                "summary": "HealthCheck",
                "operationId": "HealthCheck",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    }
                }
            }
        },
        "/stock/detail": {
            "get": {
                "description": "Get stock detail by symbol",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stock"
                ],
                "summary": "Get Stock Detail",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Stock symbol",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.StockInfo"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    }
                }
            }
        },
        "/stock/list": {
            "get": {
                "description": "Get list of active stocks (status = 'active')",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stock"
                ],
                "summary": "Get Stock List",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetStockListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    }
                }
            }
        },
        "/trade/asset": {
            "get": {
                "description": "Get a single asset information by symbol",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trade"
                ],
                "summary": "Get Asset",
                "parameters": [
                    {
                        "type": "string",
                        "example": "AAPL",
                        "description": "Asset symbol",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetAssetResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    }
                }
            }
        },
        "/trade/assets": {
            "get": {
                "description": "Get list of assets (stocks, crypto, etc.) with filtering options",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trade"
                ],
                "summary": "Get Assets",
                "parameters": [
                    {
                        "type": "string",
                        "example": "active",
                        "description": "Asset status filter (active or inactive)",
                        "name": "status",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "us_equity",
                        "description": "Asset class filter (us_equity or crypto)",
                        "name": "asset_class",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "NASDAQ",
                        "description": "Exchange name filter",
                        "name": "exchange",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetAssetsResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    }
                }
            }
        },
        "/trade/currentPrice": {
            "get": {
                "description": "Get the current price for a given symbol",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trade"
                ],
                "summary": "Get Current Price",
                "parameters": [
                    {
                        "type": "string",
                        "default": "AAPL",
                        "example": "AAPL",
                        "description": "Stock symbol",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetCurrentPriceResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    }
                }
            }
        },
        "/trade/historicalData": {
            "get": {
                "description": "Get historical price data for a given symbol",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trade"
                ],
                "summary": "Get Historical Data",
                "parameters": [
                    {
                        "type": "string",
                        "default": "AAPL",
                        "example": "AAPL",
                        "description": "Stock symbol",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1704067200,
                        "example": 1704067200,
                        "description": "Start time as Unix timestamp in seconds",
                        "name": "start_time",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 1706745599,
                        "example": 1706745599,
                        "description": "End time as Unix timestamp in seconds",
                        "name": "end_time",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1d",
                        "example": "1d",
                        "description": "Time interval. Short format: 1m, 5m, 15m, 1h, 1d, 1w. Full format: 1Min, 5Min, 15Min, 1Hour, 1Day, 1Week",
                        "name": "interval",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 100,
                        "example": 100,
                        "description": "Maximum number of records to return",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetHistoricalDataListResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    }
                }
            }
        },
        "/trade/latestQuote": {
            "get": {
                "description": "Get the latest bid/ask quote for a given symbol",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trade"
                ],
                "summary": "Get Latest Quote",
                "parameters": [
                    {
                        "type": "string",
                        "default": "AAPL",
                        "example": "AAPL",
                        "description": "Stock symbol",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetLatestQuoteResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    }
                }
            }
        },
        "/trade/marketClock": {
            "get": {
                "description": "Get the current market clock status including whether the market is open and next open/close times",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trade"
                ],
                "summary": "Get Market Clock",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetMarketClockResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    }
                }
            }
        },
        "/trade/snapshot": {
            "get": {
                "description": "Get comprehensive market snapshot for a given symbol including latest trade, quote, and bar data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Trade"
                ],
                "summary": "Get Snapshot",
                "parameters": [
                    {
                        "type": "string",
                        "default": "AAPL",
                        "example": "AAPL",
                        "description": "Stock symbol",
                        "name": "symbol",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/web.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.GetSnapshotResponse"
                                        }
                                    }
                                }
                            ]
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.Response"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.AssetDTO": {
            "type": "object",
            "properties": {
                "attributes": {
                    "description": "additional attributes",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "class": {
                    "description": "us_equity or crypto",
                    "type": "string"
                },
                "easy_to_borrow": {
                    "description": "whether the asset is easy to borrow",
                    "type": "boolean"
                },
                "exchange": {
                    "description": "exchange name",
                    "type": "string"
                },
                "fractionable": {
                    "description": "whether the asset is fractionable",
                    "type": "boolean"
                },
                "id": {
                    "type": "string"
                },
                "maintenance_margin_requirement": {
                    "description": "maintenance margin requirement",
                    "type": "integer"
                },
                "marginable": {
                    "description": "whether the asset is marginable",
                    "type": "boolean"
                },
                "name": {
                    "description": "asset name",
                    "type": "string"
                },
                "shortable": {
                    "description": "whether the asset is shortable",
                    "type": "boolean"
                },
                "status": {
                    "description": "active or inactive",
                    "type": "string"
                },
                "symbol": {
                    "description": "asset symbol",
                    "type": "string"
                },
                "tradable": {
                    "description": "whether the asset is tradable",
                    "type": "boolean"
                }
            }
        },
        "dto.BarDTO": {
            "type": "object",
            "properties": {
                "close": {
                    "type": "number"
                },
                "high": {
                    "type": "number"
                },
                "low": {
                    "type": "number"
                },
                "open": {
                    "type": "number"
                },
                "timestamp": {
                    "description": "Unix timestamp in seconds",
                    "type": "integer",
                    "example": 1704067200
                },
                "trade_count": {
                    "type": "integer"
                },
                "volume": {
                    "type": "integer"
                },
                "vwap": {
                    "type": "number"
                }
            }
        },
        "dto.GetAssetResponse": {
            "type": "object",
            "properties": {
                "asset": {
                    "$ref": "#/definitions/dto.AssetDTO"
                }
            }
        },
        "dto.GetAssetsResponse": {
            "type": "object",
            "properties": {
                "assets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.AssetDTO"
                    }
                }
            }
        },
        "dto.GetCurrentPriceResponse": {
            "type": "object",
            "properties": {
                "price": {
                    "type": "number"
                },
                "symbol": {
                    "type": "string"
                },
                "timestamp": {
                    "description": "Unix timestamp in seconds",
                    "type": "integer",
                    "example": 1704067200
                },
                "volume": {
                    "type": "number"
                }
            }
        },
        "dto.GetHistoricalDataListResponse": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.GetHistoricalDataResponse"
                    }
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "dto.GetHistoricalDataResponse": {
            "type": "object",
            "properties": {
                "close": {
                    "type": "number"
                },
                "high": {
                    "type": "number"
                },
                "low": {
                    "type": "number"
                },
                "open": {
                    "type": "number"
                },
                "timestamp": {
                    "description": "Unix timestamp in seconds",
                    "type": "integer",
                    "example": 1704067200
                },
                "volume": {
                    "type": "integer"
                }
            }
        },
        "dto.GetLatestQuoteResponse": {
            "type": "object",
            "properties": {
                "quote": {
                    "$ref": "#/definitions/dto.QuoteDTO"
                }
            }
        },
        "dto.GetMarketClockResponse": {
            "type": "object",
            "properties": {
                "is_open": {
                    "type": "boolean"
                },
                "next_close": {
                    "description": "Unix timestamp in seconds",
                    "type": "integer",
                    "example": 1704067200
                },
                "next_open": {
                    "description": "Unix timestamp in seconds",
                    "type": "integer",
                    "example": 1704067200
                },
                "timestamp": {
                    "description": "Unix timestamp in seconds",
                    "type": "integer",
                    "example": 1704067200
                }
            }
        },
        "dto.GetSnapshotResponse": {
            "type": "object",
            "properties": {
                "snapshot": {
                    "$ref": "#/definitions/dto.SnapshotData"
                }
            }
        },
        "dto.GetStockListResponse": {
            "type": "object",
            "properties": {
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.StockInfo"
                    }
                }
            }
        },
        "dto.QuoteDTO": {
            "type": "object",
            "properties": {
                "ask_exchange": {
                    "type": "string"
                },
                "ask_price": {
                    "type": "number"
                },
                "ask_size": {
                    "type": "integer"
                },
                "bid_exchange": {
                    "type": "string"
                },
                "bid_price": {
                    "type": "number"
                },
                "bid_size": {
                    "type": "integer"
                },
                "conditions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "tape": {
                    "type": "string"
                },
                "timestamp": {
                    "description": "Unix timestamp in seconds",
                    "type": "integer",
                    "example": 1704067200
                }
            }
        },
        "dto.SnapshotData": {
            "type": "object",
            "properties": {
                "daily_bar": {
                    "$ref": "#/definitions/dto.BarDTO"
                },
                "latest_quote": {
                    "$ref": "#/definitions/dto.QuoteDTO"
                },
                "latest_trade": {
                    "$ref": "#/definitions/dto.TradeDTO"
                },
                "minute_bar": {
                    "$ref": "#/definitions/dto.BarDTO"
                },
                "prev_daily_bar": {
                    "$ref": "#/definitions/dto.BarDTO"
                },
                "symbol": {
                    "type": "string"
                }
            }
        },
        "dto.StockInfo": {
            "type": "object",
            "properties": {
                "about": {
                    "type": "string"
                },
                "contract": {
                    "type": "string"
                },
                "createdAt": {
                    "description": "Unix timestamp in seconds",
                    "type": "integer",
                    "example": 1704067200
                },
                "exchange": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "symbol": {
                    "type": "string"
                },
                "updatedAt": {
                    "description": "Unix timestamp in seconds",
                    "type": "integer",
                    "example": 1704067200
                }
            }
        },
        "dto.TradeDTO": {
            "type": "object",
            "properties": {
                "conditions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "exchange": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "price": {
                    "type": "number"
                },
                "size": {
                    "type": "integer"
                },
                "tape": {
                    "type": "string"
                },
                "timestamp": {
                    "description": "Unix timestamp in seconds",
                    "type": "integer",
                    "example": 1704067200
                },
                "update": {
                    "type": "string"
                }
            }
        },
        "web.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "msg": {
                    "type": "string"
                },
                "requestId": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "description": "Rwa common-api",
            "type": "apiKey",
            "name": "X-API-Key",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "RWA API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
