// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: depth.proto

package cache_definition

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderBookOrDepthDto struct {
	state         protoimpl.MessageState     `protogen:"open.v1"`
	Amm           *LiquidityAmmDto           `protobuf:"bytes,1,opt,name=amm,proto3" json:"amm,omitempty"`
	Tids          []int64                    `protobuf:"varint,2,rep,packed,name=tids,proto3" json:"tids,omitempty"`
	Pearls        []*MinimalPearlDto         `protobuf:"bytes,3,rep,name=pearls,proto3" json:"pearls,omitempty"`
	BlockInfo     *BlockInfoDto              `protobuf:"bytes,4,opt,name=blockInfo,proto3" json:"blockInfo,omitempty"`
	TickDelta     int64                      `protobuf:"varint,5,opt,name=tickDelta,proto3" json:"tickDelta,omitempty"`
	Size          int64                      `protobuf:"varint,6,opt,name=size,proto3" json:"size,omitempty"`
	Length        int32                      `protobuf:"varint,7,opt,name=length,proto3" json:"length,omitempty"`
	StepRatio     int64                      `protobuf:"varint,8,opt,name=stepRatio,proto3" json:"stepRatio,omitempty"`
	Tick2Pearl    map[int64]*MinimalPearlDto `protobuf:"bytes,9,rep,name=tick2Pearl,proto3" json:"tick2Pearl,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IsInverse     bool                       `protobuf:"varint,10,opt,name=isInverse,proto3" json:"isInverse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookOrDepthDto) Reset() {
	*x = OrderBookOrDepthDto{}
	mi := &file_depth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookOrDepthDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookOrDepthDto) ProtoMessage() {}

func (x *OrderBookOrDepthDto) ProtoReflect() protoreflect.Message {
	mi := &file_depth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookOrDepthDto.ProtoReflect.Descriptor instead.
func (*OrderBookOrDepthDto) Descriptor() ([]byte, []int) {
	return file_depth_proto_rawDescGZIP(), []int{0}
}

func (x *OrderBookOrDepthDto) GetAmm() *LiquidityAmmDto {
	if x != nil {
		return x.Amm
	}
	return nil
}

func (x *OrderBookOrDepthDto) GetTids() []int64 {
	if x != nil {
		return x.Tids
	}
	return nil
}

func (x *OrderBookOrDepthDto) GetPearls() []*MinimalPearlDto {
	if x != nil {
		return x.Pearls
	}
	return nil
}

func (x *OrderBookOrDepthDto) GetBlockInfo() *BlockInfoDto {
	if x != nil {
		return x.BlockInfo
	}
	return nil
}

func (x *OrderBookOrDepthDto) GetTickDelta() int64 {
	if x != nil {
		return x.TickDelta
	}
	return 0
}

func (x *OrderBookOrDepthDto) GetSize() int64 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *OrderBookOrDepthDto) GetLength() int32 {
	if x != nil {
		return x.Length
	}
	return 0
}

func (x *OrderBookOrDepthDto) GetStepRatio() int64 {
	if x != nil {
		return x.StepRatio
	}
	return 0
}

func (x *OrderBookOrDepthDto) GetTick2Pearl() map[int64]*MinimalPearlDto {
	if x != nil {
		return x.Tick2Pearl
	}
	return nil
}

func (x *OrderBookOrDepthDto) GetIsInverse() bool {
	if x != nil {
		return x.IsInverse
	}
	return false
}

type LiquidityAmmDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SqrtPX96      string                 `protobuf:"bytes,1,opt,name=sqrtPX96,proto3" json:"sqrtPX96,omitempty"`
	Tick          int64                  `protobuf:"varint,2,opt,name=tick,proto3" json:"tick,omitempty"`
	Liquidity     string                 `protobuf:"bytes,3,opt,name=liquidity,proto3" json:"liquidity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LiquidityAmmDto) Reset() {
	*x = LiquidityAmmDto{}
	mi := &file_depth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LiquidityAmmDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LiquidityAmmDto) ProtoMessage() {}

func (x *LiquidityAmmDto) ProtoReflect() protoreflect.Message {
	mi := &file_depth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LiquidityAmmDto.ProtoReflect.Descriptor instead.
func (*LiquidityAmmDto) Descriptor() ([]byte, []int) {
	return file_depth_proto_rawDescGZIP(), []int{1}
}

func (x *LiquidityAmmDto) GetSqrtPX96() string {
	if x != nil {
		return x.SqrtPX96
	}
	return ""
}

func (x *LiquidityAmmDto) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *LiquidityAmmDto) GetLiquidity() string {
	if x != nil {
		return x.Liquidity
	}
	return ""
}

type MinimalPearlDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LiquidityNet  string                 `protobuf:"bytes,1,opt,name=liquidityNet,proto3" json:"liquidityNet,omitempty"`
	Left          string                 `protobuf:"bytes,2,opt,name=left,proto3" json:"left,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MinimalPearlDto) Reset() {
	*x = MinimalPearlDto{}
	mi := &file_depth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MinimalPearlDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MinimalPearlDto) ProtoMessage() {}

func (x *MinimalPearlDto) ProtoReflect() protoreflect.Message {
	mi := &file_depth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MinimalPearlDto.ProtoReflect.Descriptor instead.
func (*MinimalPearlDto) Descriptor() ([]byte, []int) {
	return file_depth_proto_rawDescGZIP(), []int{2}
}

func (x *MinimalPearlDto) GetLiquidityNet() string {
	if x != nil {
		return x.LiquidityNet
	}
	return ""
}

func (x *MinimalPearlDto) GetLeft() string {
	if x != nil {
		return x.Left
	}
	return ""
}

var File_depth_proto protoreflect.FileDescriptor

const file_depth_proto_rawDesc = "" +
	"\n" +
	"\vdepth.proto\x1a\fcommon.proto\"\xc1\x03\n" +
	"\x13OrderBookOrDepthDto\x12\"\n" +
	"\x03amm\x18\x01 \x01(\v2\x10.LiquidityAmmDtoR\x03amm\x12\x12\n" +
	"\x04tids\x18\x02 \x03(\x03R\x04tids\x12(\n" +
	"\x06pearls\x18\x03 \x03(\v2\x10.MinimalPearlDtoR\x06pearls\x12+\n" +
	"\tblockInfo\x18\x04 \x01(\v2\r.BlockInfoDtoR\tblockInfo\x12\x1c\n" +
	"\ttickDelta\x18\x05 \x01(\x03R\ttickDelta\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x03R\x04size\x12\x16\n" +
	"\x06length\x18\a \x01(\x05R\x06length\x12\x1c\n" +
	"\tstepRatio\x18\b \x01(\x03R\tstepRatio\x12D\n" +
	"\n" +
	"tick2Pearl\x18\t \x03(\v2$.OrderBookOrDepthDto.Tick2PearlEntryR\n" +
	"tick2Pearl\x12\x1c\n" +
	"\tisInverse\x18\n" +
	" \x01(\bR\tisInverse\x1aO\n" +
	"\x0fTick2PearlEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12&\n" +
	"\x05value\x18\x02 \x01(\v2\x10.MinimalPearlDtoR\x05value:\x028\x01\"_\n" +
	"\x0fLiquidityAmmDto\x12\x1a\n" +
	"\bsqrtPX96\x18\x01 \x01(\tR\bsqrtPX96\x12\x12\n" +
	"\x04tick\x18\x02 \x01(\x03R\x04tick\x12\x1c\n" +
	"\tliquidity\x18\x03 \x01(\tR\tliquidity\"I\n" +
	"\x0fMinimalPearlDto\x12\"\n" +
	"\fliquidityNet\x18\x01 \x01(\tR\fliquidityNet\x12\x12\n" +
	"\x04left\x18\x02 \x01(\tR\x04leftB\x16Z\x14../;cache_definitionb\x06proto3"

var (
	file_depth_proto_rawDescOnce sync.Once
	file_depth_proto_rawDescData []byte
)

func file_depth_proto_rawDescGZIP() []byte {
	file_depth_proto_rawDescOnce.Do(func() {
		file_depth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_depth_proto_rawDesc), len(file_depth_proto_rawDesc)))
	})
	return file_depth_proto_rawDescData
}

var file_depth_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_depth_proto_goTypes = []any{
	(*OrderBookOrDepthDto)(nil), // 0: OrderBookOrDepthDto
	(*LiquidityAmmDto)(nil),     // 1: LiquidityAmmDto
	(*MinimalPearlDto)(nil),     // 2: MinimalPearlDto
	nil,                         // 3: OrderBookOrDepthDto.Tick2PearlEntry
	(*BlockInfoDto)(nil),        // 4: BlockInfoDto
}
var file_depth_proto_depIdxs = []int32{
	1, // 0: OrderBookOrDepthDto.amm:type_name -> LiquidityAmmDto
	2, // 1: OrderBookOrDepthDto.pearls:type_name -> MinimalPearlDto
	4, // 2: OrderBookOrDepthDto.blockInfo:type_name -> BlockInfoDto
	3, // 3: OrderBookOrDepthDto.tick2Pearl:type_name -> OrderBookOrDepthDto.Tick2PearlEntry
	2, // 4: OrderBookOrDepthDto.Tick2PearlEntry.value:type_name -> MinimalPearlDto
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_depth_proto_init() }
func file_depth_proto_init() {
	if File_depth_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_depth_proto_rawDesc), len(file_depth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_depth_proto_goTypes,
		DependencyIndexes: file_depth_proto_depIdxs,
		MessageInfos:      file_depth_proto_msgTypes,
	}.Build()
	File_depth_proto = out.File
	file_depth_proto_goTypes = nil
	file_depth_proto_depIdxs = nil
}
