// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: instrument.proto

package cache_definition

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstrumentStateDetailsDot struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	InstrumentAddr     string                 `protobuf:"bytes,1,opt,name=instrumentAddr,proto3" json:"instrumentAddr,omitempty"`
	Symbol             string                 `protobuf:"bytes,2,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Market             *MarketInfo            `protobuf:"bytes,3,opt,name=market,proto3" json:"market,omitempty"`
	Condition          uint32                 `protobuf:"varint,4,opt,name=condition,proto3" json:"condition,omitempty"`
	Setting            *InstrumentSetting     `protobuf:"bytes,5,opt,name=setting,proto3" json:"setting,omitempty"`
	SpotPrice          string                 `protobuf:"bytes,6,opt,name=spotPrice,proto3" json:"spotPrice,omitempty"`
	Amms               []*AMMState            `protobuf:"bytes,7,rep,name=amms,proto3" json:"amms,omitempty"`
	Base               *TokenInfo             `protobuf:"bytes,8,opt,name=base,proto3" json:"base,omitempty"`
	Quote              *TokenInfo             `protobuf:"bytes,9,opt,name=quote,proto3" json:"quote,omitempty"`
	BlockInfo          *BlockInfoDto          `protobuf:"bytes,10,opt,name=blockInfo,proto3" json:"blockInfo,omitempty"`
	PlacePaused        bool                   `protobuf:"varint,11,opt,name=placePaused,proto3" json:"placePaused,omitempty"`
	FundingHour        uint32                 `protobuf:"varint,12,opt,name=fundingHour,proto3" json:"fundingHour,omitempty"`
	DisableOrderRebate bool                   `protobuf:"varint,13,opt,name=disableOrderRebate,proto3" json:"disableOrderRebate,omitempty"`
	InstrumentType     uint32                 `protobuf:"varint,14,opt,name=instrumentType,proto3" json:"instrumentType,omitempty"`
	MarketType         string                 `protobuf:"bytes,15,opt,name=marketType,proto3" json:"marketType,omitempty"`
	MinTradeValue      string                 `protobuf:"bytes,16,opt,name=minTradeValue,proto3" json:"minTradeValue,omitempty"`
	MinOrderValue      string                 `protobuf:"bytes,17,opt,name=minOrderValue,proto3" json:"minOrderValue,omitempty"`
	MinRangeValue      string                 `protobuf:"bytes,18,opt,name=minRangeValue,proto3" json:"minRangeValue,omitempty"`
	DisplayBase        *TokenInfo             `protobuf:"bytes,19,opt,name=displayBase,proto3" json:"displayBase,omitempty"`
	DisplayQuote       *TokenInfo             `protobuf:"bytes,20,opt,name=displayQuote,proto3" json:"displayQuote,omitempty"`
	MinTickDelta       uint32                 `protobuf:"varint,21,opt,name=minTickDelta,proto3" json:"minTickDelta,omitempty"`
	Index              uint64                 `protobuf:"varint,22,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *InstrumentStateDetailsDot) Reset() {
	*x = InstrumentStateDetailsDot{}
	mi := &file_instrument_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrumentStateDetailsDot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrumentStateDetailsDot) ProtoMessage() {}

func (x *InstrumentStateDetailsDot) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrumentStateDetailsDot.ProtoReflect.Descriptor instead.
func (*InstrumentStateDetailsDot) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{0}
}

func (x *InstrumentStateDetailsDot) GetInstrumentAddr() string {
	if x != nil {
		return x.InstrumentAddr
	}
	return ""
}

func (x *InstrumentStateDetailsDot) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *InstrumentStateDetailsDot) GetMarket() *MarketInfo {
	if x != nil {
		return x.Market
	}
	return nil
}

func (x *InstrumentStateDetailsDot) GetCondition() uint32 {
	if x != nil {
		return x.Condition
	}
	return 0
}

func (x *InstrumentStateDetailsDot) GetSetting() *InstrumentSetting {
	if x != nil {
		return x.Setting
	}
	return nil
}

func (x *InstrumentStateDetailsDot) GetSpotPrice() string {
	if x != nil {
		return x.SpotPrice
	}
	return ""
}

func (x *InstrumentStateDetailsDot) GetAmms() []*AMMState {
	if x != nil {
		return x.Amms
	}
	return nil
}

func (x *InstrumentStateDetailsDot) GetBase() *TokenInfo {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *InstrumentStateDetailsDot) GetQuote() *TokenInfo {
	if x != nil {
		return x.Quote
	}
	return nil
}

func (x *InstrumentStateDetailsDot) GetBlockInfo() *BlockInfoDto {
	if x != nil {
		return x.BlockInfo
	}
	return nil
}

func (x *InstrumentStateDetailsDot) GetPlacePaused() bool {
	if x != nil {
		return x.PlacePaused
	}
	return false
}

func (x *InstrumentStateDetailsDot) GetFundingHour() uint32 {
	if x != nil {
		return x.FundingHour
	}
	return 0
}

func (x *InstrumentStateDetailsDot) GetDisableOrderRebate() bool {
	if x != nil {
		return x.DisableOrderRebate
	}
	return false
}

func (x *InstrumentStateDetailsDot) GetInstrumentType() uint32 {
	if x != nil {
		return x.InstrumentType
	}
	return 0
}

func (x *InstrumentStateDetailsDot) GetMarketType() string {
	if x != nil {
		return x.MarketType
	}
	return ""
}

func (x *InstrumentStateDetailsDot) GetMinTradeValue() string {
	if x != nil {
		return x.MinTradeValue
	}
	return ""
}

func (x *InstrumentStateDetailsDot) GetMinOrderValue() string {
	if x != nil {
		return x.MinOrderValue
	}
	return ""
}

func (x *InstrumentStateDetailsDot) GetMinRangeValue() string {
	if x != nil {
		return x.MinRangeValue
	}
	return ""
}

func (x *InstrumentStateDetailsDot) GetDisplayBase() *TokenInfo {
	if x != nil {
		return x.DisplayBase
	}
	return nil
}

func (x *InstrumentStateDetailsDot) GetDisplayQuote() *TokenInfo {
	if x != nil {
		return x.DisplayQuote
	}
	return nil
}

func (x *InstrumentStateDetailsDot) GetMinTickDelta() uint32 {
	if x != nil {
		return x.MinTickDelta
	}
	return 0
}

func (x *InstrumentStateDetailsDot) GetIndex() uint64 {
	if x != nil {
		return x.Index
	}
	return 0
}

type MarketInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *MarketInfoDetails     `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	Config        *MarketConfig          `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
	Feeder        *MarketFeeder          `protobuf:"bytes,3,opt,name=feeder,proto3" json:"feeder,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketInfo) Reset() {
	*x = MarketInfo{}
	mi := &file_instrument_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketInfo) ProtoMessage() {}

func (x *MarketInfo) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketInfo.ProtoReflect.Descriptor instead.
func (*MarketInfo) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{1}
}

func (x *MarketInfo) GetInfo() *MarketInfoDetails {
	if x != nil {
		return x.Info
	}
	return nil
}

func (x *MarketInfo) GetConfig() *MarketConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *MarketInfo) GetFeeder() *MarketFeeder {
	if x != nil {
		return x.Feeder
	}
	return nil
}

type MarketInfoDetails struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Addr          string                 `protobuf:"bytes,1,opt,name=addr,proto3" json:"addr,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Beacon        string                 `protobuf:"bytes,3,opt,name=beacon,proto3" json:"beacon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketInfoDetails) Reset() {
	*x = MarketInfoDetails{}
	mi := &file_instrument_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketInfoDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketInfoDetails) ProtoMessage() {}

func (x *MarketInfoDetails) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketInfoDetails.ProtoReflect.Descriptor instead.
func (*MarketInfoDetails) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{2}
}

func (x *MarketInfoDetails) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *MarketInfoDetails) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *MarketInfoDetails) GetBeacon() string {
	if x != nil {
		return x.Beacon
	}
	return ""
}

type MarketConfig struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DailyInterestRate uint32                 `protobuf:"varint,1,opt,name=dailyInterestRate,proto3" json:"dailyInterestRate,omitempty"`
	FeederSource      []*FeederSource        `protobuf:"bytes,2,rep,name=feederSource,proto3" json:"feederSource,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *MarketConfig) Reset() {
	*x = MarketConfig{}
	mi := &file_instrument_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketConfig) ProtoMessage() {}

func (x *MarketConfig) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketConfig.ProtoReflect.Descriptor instead.
func (*MarketConfig) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{3}
}

func (x *MarketConfig) GetDailyInterestRate() uint32 {
	if x != nil {
		return x.DailyInterestRate
	}
	return 0
}

func (x *MarketConfig) GetFeederSource() []*FeederSource {
	if x != nil {
		return x.FeederSource
	}
	return nil
}

type FeederSource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BaseSymbol    string                 `protobuf:"bytes,1,opt,name=baseSymbol,proto3" json:"baseSymbol,omitempty"`
	QuoteSymbol   string                 `protobuf:"bytes,2,opt,name=quoteSymbol,proto3" json:"quoteSymbol,omitempty"`
	Ftype         uint32                 `protobuf:"varint,3,opt,name=ftype,proto3" json:"ftype,omitempty"`
	Aggregator0   string                 `protobuf:"bytes,4,opt,name=aggregator0,proto3" json:"aggregator0,omitempty"`
	HeartBeat0    uint32                 `protobuf:"varint,5,opt,name=heartBeat0,proto3" json:"heartBeat0,omitempty"`
	Aggregator1   string                 `protobuf:"bytes,6,opt,name=aggregator1,proto3" json:"aggregator1,omitempty"`
	HeartBeat1    uint32                 `protobuf:"varint,7,opt,name=heartBeat1,proto3" json:"heartBeat1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FeederSource) Reset() {
	*x = FeederSource{}
	mi := &file_instrument_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FeederSource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeederSource) ProtoMessage() {}

func (x *FeederSource) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeederSource.ProtoReflect.Descriptor instead.
func (*FeederSource) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{4}
}

func (x *FeederSource) GetBaseSymbol() string {
	if x != nil {
		return x.BaseSymbol
	}
	return ""
}

func (x *FeederSource) GetQuoteSymbol() string {
	if x != nil {
		return x.QuoteSymbol
	}
	return ""
}

func (x *FeederSource) GetFtype() uint32 {
	if x != nil {
		return x.Ftype
	}
	return 0
}

func (x *FeederSource) GetAggregator0() string {
	if x != nil {
		return x.Aggregator0
	}
	return ""
}

func (x *FeederSource) GetHeartBeat0() uint32 {
	if x != nil {
		return x.HeartBeat0
	}
	return 0
}

func (x *FeederSource) GetAggregator1() string {
	if x != nil {
		return x.Aggregator1
	}
	return ""
}

func (x *FeederSource) GetHeartBeat1() uint32 {
	if x != nil {
		return x.HeartBeat1
	}
	return 0
}

type MarketFeeder struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ftype         uint32                 `protobuf:"varint,1,opt,name=ftype,proto3" json:"ftype,omitempty"`
	Scaler0       string                 `protobuf:"bytes,2,opt,name=scaler0,proto3" json:"scaler0,omitempty"`
	Aggregator0   string                 `protobuf:"bytes,3,opt,name=aggregator0,proto3" json:"aggregator0,omitempty"`
	HeartBeat0    uint32                 `protobuf:"varint,4,opt,name=heartBeat0,proto3" json:"heartBeat0,omitempty"`
	Scaler1       string                 `protobuf:"bytes,5,opt,name=scaler1,proto3" json:"scaler1,omitempty"`
	Aggregator1   string                 `protobuf:"bytes,6,opt,name=aggregator1,proto3" json:"aggregator1,omitempty"`
	HeartBeat1    uint32                 `protobuf:"varint,7,opt,name=heartBeat1,proto3" json:"heartBeat1,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarketFeeder) Reset() {
	*x = MarketFeeder{}
	mi := &file_instrument_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketFeeder) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketFeeder) ProtoMessage() {}

func (x *MarketFeeder) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketFeeder.ProtoReflect.Descriptor instead.
func (*MarketFeeder) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{5}
}

func (x *MarketFeeder) GetFtype() uint32 {
	if x != nil {
		return x.Ftype
	}
	return 0
}

func (x *MarketFeeder) GetScaler0() string {
	if x != nil {
		return x.Scaler0
	}
	return ""
}

func (x *MarketFeeder) GetAggregator0() string {
	if x != nil {
		return x.Aggregator0
	}
	return ""
}

func (x *MarketFeeder) GetHeartBeat0() uint32 {
	if x != nil {
		return x.HeartBeat0
	}
	return 0
}

func (x *MarketFeeder) GetScaler1() string {
	if x != nil {
		return x.Scaler1
	}
	return ""
}

func (x *MarketFeeder) GetAggregator1() string {
	if x != nil {
		return x.Aggregator1
	}
	return ""
}

func (x *MarketFeeder) GetHeartBeat1() uint32 {
	if x != nil {
		return x.HeartBeat1
	}
	return 0
}

type TokenInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Symbol        string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	Decimals      uint32                 `protobuf:"varint,3,opt,name=decimals,proto3" json:"decimals,omitempty"`
	Name          string                 `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenInfo) Reset() {
	*x = TokenInfo{}
	mi := &file_instrument_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenInfo) ProtoMessage() {}

func (x *TokenInfo) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenInfo.ProtoReflect.Descriptor instead.
func (*TokenInfo) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{6}
}

func (x *TokenInfo) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TokenInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TokenInfo) GetDecimals() uint32 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *TokenInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type AMMState struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Expiry               uint32                 `protobuf:"varint,1,opt,name=expiry,proto3" json:"expiry,omitempty"`
	Timestamp            uint32                 `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Status               uint32                 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Tick                 int64                  `protobuf:"varint,4,opt,name=tick,proto3" json:"tick,omitempty"`
	SqrtPX96             string                 `protobuf:"bytes,5,opt,name=sqrtPX96,proto3" json:"sqrtPX96,omitempty"`
	Liquidity            string                 `protobuf:"bytes,6,opt,name=liquidity,proto3" json:"liquidity,omitempty"`
	TotalLiquidity       string                 `protobuf:"bytes,7,opt,name=totalLiquidity,proto3" json:"totalLiquidity,omitempty"`
	TotalShort           string                 `protobuf:"bytes,8,opt,name=totalShort,proto3" json:"totalShort,omitempty"`
	OpenInterests        string                 `protobuf:"bytes,9,opt,name=openInterests,proto3" json:"openInterests,omitempty"`
	TotalLong            string                 `protobuf:"bytes,10,opt,name=totalLong,proto3" json:"totalLong,omitempty"`
	InvolvedFund         string                 `protobuf:"bytes,11,opt,name=involvedFund,proto3" json:"involvedFund,omitempty"`
	FeeIndex             string                 `protobuf:"bytes,12,opt,name=feeIndex,proto3" json:"feeIndex,omitempty"`
	ProtocolFee          string                 `protobuf:"bytes,13,opt,name=protocolFee,proto3" json:"protocolFee,omitempty"`
	LongSocialLossIndex  string                 `protobuf:"bytes,14,opt,name=longSocialLossIndex,proto3" json:"longSocialLossIndex,omitempty"`
	ShortSocialLossIndex string                 `protobuf:"bytes,15,opt,name=shortSocialLossIndex,proto3" json:"shortSocialLossIndex,omitempty"`
	LongFundingIndex     string                 `protobuf:"bytes,16,opt,name=longFundingIndex,proto3" json:"longFundingIndex,omitempty"`
	ShortFundingIndex    string                 `protobuf:"bytes,17,opt,name=shortFundingIndex,proto3" json:"shortFundingIndex,omitempty"`
	InsuranceFund        string                 `protobuf:"bytes,18,opt,name=insuranceFund,proto3" json:"insuranceFund,omitempty"`
	SettlementPrice      string                 `protobuf:"bytes,19,opt,name=settlementPrice,proto3" json:"settlementPrice,omitempty"`
	InstrumentAddr       string                 `protobuf:"bytes,20,opt,name=instrumentAddr,proto3" json:"instrumentAddr,omitempty"`
	MarkPrice            string                 `protobuf:"bytes,21,opt,name=markPrice,proto3" json:"markPrice,omitempty"`
	BlockInfo            *BlockInfoDto          `protobuf:"bytes,22,opt,name=blockInfo,proto3" json:"blockInfo,omitempty"`
	FairPrice            string                 `protobuf:"bytes,23,opt,name=fairPrice,proto3" json:"fairPrice,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *AMMState) Reset() {
	*x = AMMState{}
	mi := &file_instrument_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AMMState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AMMState) ProtoMessage() {}

func (x *AMMState) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AMMState.ProtoReflect.Descriptor instead.
func (*AMMState) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{7}
}

func (x *AMMState) GetExpiry() uint32 {
	if x != nil {
		return x.Expiry
	}
	return 0
}

func (x *AMMState) GetTimestamp() uint32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *AMMState) GetStatus() uint32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AMMState) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *AMMState) GetSqrtPX96() string {
	if x != nil {
		return x.SqrtPX96
	}
	return ""
}

func (x *AMMState) GetLiquidity() string {
	if x != nil {
		return x.Liquidity
	}
	return ""
}

func (x *AMMState) GetTotalLiquidity() string {
	if x != nil {
		return x.TotalLiquidity
	}
	return ""
}

func (x *AMMState) GetTotalShort() string {
	if x != nil {
		return x.TotalShort
	}
	return ""
}

func (x *AMMState) GetOpenInterests() string {
	if x != nil {
		return x.OpenInterests
	}
	return ""
}

func (x *AMMState) GetTotalLong() string {
	if x != nil {
		return x.TotalLong
	}
	return ""
}

func (x *AMMState) GetInvolvedFund() string {
	if x != nil {
		return x.InvolvedFund
	}
	return ""
}

func (x *AMMState) GetFeeIndex() string {
	if x != nil {
		return x.FeeIndex
	}
	return ""
}

func (x *AMMState) GetProtocolFee() string {
	if x != nil {
		return x.ProtocolFee
	}
	return ""
}

func (x *AMMState) GetLongSocialLossIndex() string {
	if x != nil {
		return x.LongSocialLossIndex
	}
	return ""
}

func (x *AMMState) GetShortSocialLossIndex() string {
	if x != nil {
		return x.ShortSocialLossIndex
	}
	return ""
}

func (x *AMMState) GetLongFundingIndex() string {
	if x != nil {
		return x.LongFundingIndex
	}
	return ""
}

func (x *AMMState) GetShortFundingIndex() string {
	if x != nil {
		return x.ShortFundingIndex
	}
	return ""
}

func (x *AMMState) GetInsuranceFund() string {
	if x != nil {
		return x.InsuranceFund
	}
	return ""
}

func (x *AMMState) GetSettlementPrice() string {
	if x != nil {
		return x.SettlementPrice
	}
	return ""
}

func (x *AMMState) GetInstrumentAddr() string {
	if x != nil {
		return x.InstrumentAddr
	}
	return ""
}

func (x *AMMState) GetMarkPrice() string {
	if x != nil {
		return x.MarkPrice
	}
	return ""
}

func (x *AMMState) GetBlockInfo() *BlockInfoDto {
	if x != nil {
		return x.BlockInfo
	}
	return nil
}

func (x *AMMState) GetFairPrice() string {
	if x != nil {
		return x.FairPrice
	}
	return ""
}

type InstrumentSetting struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	InitialMarginRatio     uint32                 `protobuf:"varint,1,opt,name=initialMarginRatio,proto3" json:"initialMarginRatio,omitempty"`
	MaintenanceMarginRatio uint32                 `protobuf:"varint,2,opt,name=maintenanceMarginRatio,proto3" json:"maintenanceMarginRatio,omitempty"`
	QuoteParam             *QuoteParam            `protobuf:"bytes,3,opt,name=quoteParam,proto3" json:"quoteParam,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *InstrumentSetting) Reset() {
	*x = InstrumentSetting{}
	mi := &file_instrument_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstrumentSetting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstrumentSetting) ProtoMessage() {}

func (x *InstrumentSetting) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstrumentSetting.ProtoReflect.Descriptor instead.
func (*InstrumentSetting) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{8}
}

func (x *InstrumentSetting) GetInitialMarginRatio() uint32 {
	if x != nil {
		return x.InitialMarginRatio
	}
	return 0
}

func (x *InstrumentSetting) GetMaintenanceMarginRatio() uint32 {
	if x != nil {
		return x.MaintenanceMarginRatio
	}
	return 0
}

func (x *InstrumentSetting) GetQuoteParam() *QuoteParam {
	if x != nil {
		return x.QuoteParam
	}
	return nil
}

type QuoteParam struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MinMarginAmount  string                 `protobuf:"bytes,1,opt,name=minMarginAmount,proto3" json:"minMarginAmount,omitempty"`
	TradingFeeRatio  uint32                 `protobuf:"varint,2,opt,name=tradingFeeRatio,proto3" json:"tradingFeeRatio,omitempty"`
	ProtocolFeeRatio uint32                 `protobuf:"varint,3,opt,name=protocolFeeRatio,proto3" json:"protocolFeeRatio,omitempty"`
	Qtype            uint32                 `protobuf:"varint,4,opt,name=qtype,proto3" json:"qtype,omitempty"`
	Tip              string                 `protobuf:"bytes,5,opt,name=tip,proto3" json:"tip,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *QuoteParam) Reset() {
	*x = QuoteParam{}
	mi := &file_instrument_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QuoteParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QuoteParam) ProtoMessage() {}

func (x *QuoteParam) ProtoReflect() protoreflect.Message {
	mi := &file_instrument_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QuoteParam.ProtoReflect.Descriptor instead.
func (*QuoteParam) Descriptor() ([]byte, []int) {
	return file_instrument_proto_rawDescGZIP(), []int{9}
}

func (x *QuoteParam) GetMinMarginAmount() string {
	if x != nil {
		return x.MinMarginAmount
	}
	return ""
}

func (x *QuoteParam) GetTradingFeeRatio() uint32 {
	if x != nil {
		return x.TradingFeeRatio
	}
	return 0
}

func (x *QuoteParam) GetProtocolFeeRatio() uint32 {
	if x != nil {
		return x.ProtocolFeeRatio
	}
	return 0
}

func (x *QuoteParam) GetQtype() uint32 {
	if x != nil {
		return x.Qtype
	}
	return 0
}

func (x *QuoteParam) GetTip() string {
	if x != nil {
		return x.Tip
	}
	return ""
}

var File_instrument_proto protoreflect.FileDescriptor

const file_instrument_proto_rawDesc = "" +
	"\n" +
	"\x10instrument.proto\x1a\fcommon.proto\"\xbe\x06\n" +
	"\x19InstrumentStateDetailsDot\x12&\n" +
	"\x0einstrumentAddr\x18\x01 \x01(\tR\x0einstrumentAddr\x12\x16\n" +
	"\x06symbol\x18\x02 \x01(\tR\x06symbol\x12#\n" +
	"\x06market\x18\x03 \x01(\v2\v.MarketInfoR\x06market\x12\x1c\n" +
	"\tcondition\x18\x04 \x01(\rR\tcondition\x12,\n" +
	"\asetting\x18\x05 \x01(\v2\x12.InstrumentSettingR\asetting\x12\x1c\n" +
	"\tspotPrice\x18\x06 \x01(\tR\tspotPrice\x12\x1d\n" +
	"\x04amms\x18\a \x03(\v2\t.AMMStateR\x04amms\x12\x1e\n" +
	"\x04base\x18\b \x01(\v2\n" +
	".TokenInfoR\x04base\x12 \n" +
	"\x05quote\x18\t \x01(\v2\n" +
	".TokenInfoR\x05quote\x12+\n" +
	"\tblockInfo\x18\n" +
	" \x01(\v2\r.BlockInfoDtoR\tblockInfo\x12 \n" +
	"\vplacePaused\x18\v \x01(\bR\vplacePaused\x12 \n" +
	"\vfundingHour\x18\f \x01(\rR\vfundingHour\x12.\n" +
	"\x12disableOrderRebate\x18\r \x01(\bR\x12disableOrderRebate\x12&\n" +
	"\x0einstrumentType\x18\x0e \x01(\rR\x0einstrumentType\x12\x1e\n" +
	"\n" +
	"marketType\x18\x0f \x01(\tR\n" +
	"marketType\x12$\n" +
	"\rminTradeValue\x18\x10 \x01(\tR\rminTradeValue\x12$\n" +
	"\rminOrderValue\x18\x11 \x01(\tR\rminOrderValue\x12$\n" +
	"\rminRangeValue\x18\x12 \x01(\tR\rminRangeValue\x12,\n" +
	"\vdisplayBase\x18\x13 \x01(\v2\n" +
	".TokenInfoR\vdisplayBase\x12.\n" +
	"\fdisplayQuote\x18\x14 \x01(\v2\n" +
	".TokenInfoR\fdisplayQuote\x12\"\n" +
	"\fminTickDelta\x18\x15 \x01(\rR\fminTickDelta\x12\x14\n" +
	"\x05index\x18\x16 \x01(\x04R\x05index\"\x82\x01\n" +
	"\n" +
	"MarketInfo\x12&\n" +
	"\x04info\x18\x01 \x01(\v2\x12.MarketInfoDetailsR\x04info\x12%\n" +
	"\x06config\x18\x02 \x01(\v2\r.MarketConfigR\x06config\x12%\n" +
	"\x06feeder\x18\x03 \x01(\v2\r.MarketFeederR\x06feeder\"S\n" +
	"\x11MarketInfoDetails\x12\x12\n" +
	"\x04addr\x18\x01 \x01(\tR\x04addr\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x16\n" +
	"\x06beacon\x18\x03 \x01(\tR\x06beacon\"o\n" +
	"\fMarketConfig\x12,\n" +
	"\x11dailyInterestRate\x18\x01 \x01(\rR\x11dailyInterestRate\x121\n" +
	"\ffeederSource\x18\x02 \x03(\v2\r.FeederSourceR\ffeederSource\"\xea\x01\n" +
	"\fFeederSource\x12\x1e\n" +
	"\n" +
	"baseSymbol\x18\x01 \x01(\tR\n" +
	"baseSymbol\x12 \n" +
	"\vquoteSymbol\x18\x02 \x01(\tR\vquoteSymbol\x12\x14\n" +
	"\x05ftype\x18\x03 \x01(\rR\x05ftype\x12 \n" +
	"\vaggregator0\x18\x04 \x01(\tR\vaggregator0\x12\x1e\n" +
	"\n" +
	"heartBeat0\x18\x05 \x01(\rR\n" +
	"heartBeat0\x12 \n" +
	"\vaggregator1\x18\x06 \x01(\tR\vaggregator1\x12\x1e\n" +
	"\n" +
	"heartBeat1\x18\a \x01(\rR\n" +
	"heartBeat1\"\xdc\x01\n" +
	"\fMarketFeeder\x12\x14\n" +
	"\x05ftype\x18\x01 \x01(\rR\x05ftype\x12\x18\n" +
	"\ascaler0\x18\x02 \x01(\tR\ascaler0\x12 \n" +
	"\vaggregator0\x18\x03 \x01(\tR\vaggregator0\x12\x1e\n" +
	"\n" +
	"heartBeat0\x18\x04 \x01(\rR\n" +
	"heartBeat0\x12\x18\n" +
	"\ascaler1\x18\x05 \x01(\tR\ascaler1\x12 \n" +
	"\vaggregator1\x18\x06 \x01(\tR\vaggregator1\x12\x1e\n" +
	"\n" +
	"heartBeat1\x18\a \x01(\rR\n" +
	"heartBeat1\"m\n" +
	"\tTokenInfo\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1a\n" +
	"\bdecimals\x18\x03 \x01(\rR\bdecimals\x12\x12\n" +
	"\x04name\x18\x04 \x01(\tR\x04name\"\xb5\x06\n" +
	"\bAMMState\x12\x16\n" +
	"\x06expiry\x18\x01 \x01(\rR\x06expiry\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\rR\ttimestamp\x12\x16\n" +
	"\x06status\x18\x03 \x01(\rR\x06status\x12\x12\n" +
	"\x04tick\x18\x04 \x01(\x03R\x04tick\x12\x1a\n" +
	"\bsqrtPX96\x18\x05 \x01(\tR\bsqrtPX96\x12\x1c\n" +
	"\tliquidity\x18\x06 \x01(\tR\tliquidity\x12&\n" +
	"\x0etotalLiquidity\x18\a \x01(\tR\x0etotalLiquidity\x12\x1e\n" +
	"\n" +
	"totalShort\x18\b \x01(\tR\n" +
	"totalShort\x12$\n" +
	"\ropenInterests\x18\t \x01(\tR\ropenInterests\x12\x1c\n" +
	"\ttotalLong\x18\n" +
	" \x01(\tR\ttotalLong\x12\"\n" +
	"\finvolvedFund\x18\v \x01(\tR\finvolvedFund\x12\x1a\n" +
	"\bfeeIndex\x18\f \x01(\tR\bfeeIndex\x12 \n" +
	"\vprotocolFee\x18\r \x01(\tR\vprotocolFee\x120\n" +
	"\x13longSocialLossIndex\x18\x0e \x01(\tR\x13longSocialLossIndex\x122\n" +
	"\x14shortSocialLossIndex\x18\x0f \x01(\tR\x14shortSocialLossIndex\x12*\n" +
	"\x10longFundingIndex\x18\x10 \x01(\tR\x10longFundingIndex\x12,\n" +
	"\x11shortFundingIndex\x18\x11 \x01(\tR\x11shortFundingIndex\x12$\n" +
	"\rinsuranceFund\x18\x12 \x01(\tR\rinsuranceFund\x12(\n" +
	"\x0fsettlementPrice\x18\x13 \x01(\tR\x0fsettlementPrice\x12&\n" +
	"\x0einstrumentAddr\x18\x14 \x01(\tR\x0einstrumentAddr\x12\x1c\n" +
	"\tmarkPrice\x18\x15 \x01(\tR\tmarkPrice\x12+\n" +
	"\tblockInfo\x18\x16 \x01(\v2\r.BlockInfoDtoR\tblockInfo\x12\x1c\n" +
	"\tfairPrice\x18\x17 \x01(\tR\tfairPrice\"\xa8\x01\n" +
	"\x11InstrumentSetting\x12.\n" +
	"\x12initialMarginRatio\x18\x01 \x01(\rR\x12initialMarginRatio\x126\n" +
	"\x16maintenanceMarginRatio\x18\x02 \x01(\rR\x16maintenanceMarginRatio\x12+\n" +
	"\n" +
	"quoteParam\x18\x03 \x01(\v2\v.QuoteParamR\n" +
	"quoteParam\"\xb4\x01\n" +
	"\n" +
	"QuoteParam\x12(\n" +
	"\x0fminMarginAmount\x18\x01 \x01(\tR\x0fminMarginAmount\x12(\n" +
	"\x0ftradingFeeRatio\x18\x02 \x01(\rR\x0ftradingFeeRatio\x12*\n" +
	"\x10protocolFeeRatio\x18\x03 \x01(\rR\x10protocolFeeRatio\x12\x14\n" +
	"\x05qtype\x18\x04 \x01(\rR\x05qtype\x12\x10\n" +
	"\x03tip\x18\x05 \x01(\tR\x03tipB\x16Z\x14../;cache_definitionb\x06proto3"

var (
	file_instrument_proto_rawDescOnce sync.Once
	file_instrument_proto_rawDescData []byte
)

func file_instrument_proto_rawDescGZIP() []byte {
	file_instrument_proto_rawDescOnce.Do(func() {
		file_instrument_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_instrument_proto_rawDesc), len(file_instrument_proto_rawDesc)))
	})
	return file_instrument_proto_rawDescData
}

var file_instrument_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_instrument_proto_goTypes = []any{
	(*InstrumentStateDetailsDot)(nil), // 0: InstrumentStateDetailsDot
	(*MarketInfo)(nil),                // 1: MarketInfo
	(*MarketInfoDetails)(nil),         // 2: MarketInfoDetails
	(*MarketConfig)(nil),              // 3: MarketConfig
	(*FeederSource)(nil),              // 4: FeederSource
	(*MarketFeeder)(nil),              // 5: MarketFeeder
	(*TokenInfo)(nil),                 // 6: TokenInfo
	(*AMMState)(nil),                  // 7: AMMState
	(*InstrumentSetting)(nil),         // 8: InstrumentSetting
	(*QuoteParam)(nil),                // 9: QuoteParam
	(*BlockInfoDto)(nil),              // 10: BlockInfoDto
}
var file_instrument_proto_depIdxs = []int32{
	1,  // 0: InstrumentStateDetailsDot.market:type_name -> MarketInfo
	8,  // 1: InstrumentStateDetailsDot.setting:type_name -> InstrumentSetting
	7,  // 2: InstrumentStateDetailsDot.amms:type_name -> AMMState
	6,  // 3: InstrumentStateDetailsDot.base:type_name -> TokenInfo
	6,  // 4: InstrumentStateDetailsDot.quote:type_name -> TokenInfo
	10, // 5: InstrumentStateDetailsDot.blockInfo:type_name -> BlockInfoDto
	6,  // 6: InstrumentStateDetailsDot.displayBase:type_name -> TokenInfo
	6,  // 7: InstrumentStateDetailsDot.displayQuote:type_name -> TokenInfo
	2,  // 8: MarketInfo.info:type_name -> MarketInfoDetails
	3,  // 9: MarketInfo.config:type_name -> MarketConfig
	5,  // 10: MarketInfo.feeder:type_name -> MarketFeeder
	4,  // 11: MarketConfig.feederSource:type_name -> FeederSource
	10, // 12: AMMState.blockInfo:type_name -> BlockInfoDto
	9,  // 13: InstrumentSetting.quoteParam:type_name -> QuoteParam
	14, // [14:14] is the sub-list for method output_type
	14, // [14:14] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_instrument_proto_init() }
func file_instrument_proto_init() {
	if File_instrument_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_instrument_proto_rawDesc), len(file_instrument_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_instrument_proto_goTypes,
		DependencyIndexes: file_instrument_proto_depIdxs,
		MessageInfos:      file_instrument_proto_msgTypes,
	}.Build()
	File_instrument_proto = out.File
	file_instrument_proto_goTypes = nil
	file_instrument_proto_depIdxs = nil
}
