// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: order_book.proto

package cache_definition

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OrderBookCacheDto struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	BlockInfo     *BlockInfoDto               `protobuf:"bytes,1,opt,name=blockInfo,proto3" json:"blockInfo,omitempty"`
	Bids          []*OrderBookCacheDetailsDto `protobuf:"bytes,2,rep,name=bids,proto3" json:"bids,omitempty"`
	Asks          []*OrderBookCacheDetailsDto `protobuf:"bytes,3,rep,name=asks,proto3" json:"asks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookCacheDto) Reset() {
	*x = OrderBookCacheDto{}
	mi := &file_order_book_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookCacheDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookCacheDto) ProtoMessage() {}

func (x *OrderBookCacheDto) ProtoReflect() protoreflect.Message {
	mi := &file_order_book_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookCacheDto.ProtoReflect.Descriptor instead.
func (*OrderBookCacheDto) Descriptor() ([]byte, []int) {
	return file_order_book_proto_rawDescGZIP(), []int{0}
}

func (x *OrderBookCacheDto) GetBlockInfo() *BlockInfoDto {
	if x != nil {
		return x.BlockInfo
	}
	return nil
}

func (x *OrderBookCacheDto) GetBids() []*OrderBookCacheDetailsDto {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *OrderBookCacheDto) GetAsks() []*OrderBookCacheDetailsDto {
	if x != nil {
		return x.Asks
	}
	return nil
}

type OrderBookCacheDetailsDto struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tick          int64                  `protobuf:"varint,1,opt,name=tick,proto3" json:"tick,omitempty"`
	Price         string                 `protobuf:"bytes,2,opt,name=price,proto3" json:"price,omitempty"`
	BaseSize      string                 `protobuf:"bytes,3,opt,name=baseSize,proto3" json:"baseSize,omitempty"`
	QuoteSize     string                 `protobuf:"bytes,4,opt,name=quoteSize,proto3" json:"quoteSize,omitempty"`
	BaseSum       string                 `protobuf:"bytes,5,opt,name=baseSum,proto3" json:"baseSum,omitempty"`
	QuoteSum      string                 `protobuf:"bytes,6,opt,name=quoteSum,proto3" json:"quoteSum,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderBookCacheDetailsDto) Reset() {
	*x = OrderBookCacheDetailsDto{}
	mi := &file_order_book_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderBookCacheDetailsDto) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderBookCacheDetailsDto) ProtoMessage() {}

func (x *OrderBookCacheDetailsDto) ProtoReflect() protoreflect.Message {
	mi := &file_order_book_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderBookCacheDetailsDto.ProtoReflect.Descriptor instead.
func (*OrderBookCacheDetailsDto) Descriptor() ([]byte, []int) {
	return file_order_book_proto_rawDescGZIP(), []int{1}
}

func (x *OrderBookCacheDetailsDto) GetTick() int64 {
	if x != nil {
		return x.Tick
	}
	return 0
}

func (x *OrderBookCacheDetailsDto) GetPrice() string {
	if x != nil {
		return x.Price
	}
	return ""
}

func (x *OrderBookCacheDetailsDto) GetBaseSize() string {
	if x != nil {
		return x.BaseSize
	}
	return ""
}

func (x *OrderBookCacheDetailsDto) GetQuoteSize() string {
	if x != nil {
		return x.QuoteSize
	}
	return ""
}

func (x *OrderBookCacheDetailsDto) GetBaseSum() string {
	if x != nil {
		return x.BaseSum
	}
	return ""
}

func (x *OrderBookCacheDetailsDto) GetQuoteSum() string {
	if x != nil {
		return x.QuoteSum
	}
	return ""
}

var File_order_book_proto protoreflect.FileDescriptor

const file_order_book_proto_rawDesc = "" +
	"\n" +
	"\x10order_book.proto\x1a\fcommon.proto\"\x9e\x01\n" +
	"\x11OrderBookCacheDto\x12+\n" +
	"\tblockInfo\x18\x01 \x01(\v2\r.BlockInfoDtoR\tblockInfo\x12-\n" +
	"\x04bids\x18\x02 \x03(\v2\x19.OrderBookCacheDetailsDtoR\x04bids\x12-\n" +
	"\x04asks\x18\x03 \x03(\v2\x19.OrderBookCacheDetailsDtoR\x04asks\"\xb4\x01\n" +
	"\x18OrderBookCacheDetailsDto\x12\x12\n" +
	"\x04tick\x18\x01 \x01(\x03R\x04tick\x12\x14\n" +
	"\x05price\x18\x02 \x01(\tR\x05price\x12\x1a\n" +
	"\bbaseSize\x18\x03 \x01(\tR\bbaseSize\x12\x1c\n" +
	"\tquoteSize\x18\x04 \x01(\tR\tquoteSize\x12\x18\n" +
	"\abaseSum\x18\x05 \x01(\tR\abaseSum\x12\x1a\n" +
	"\bquoteSum\x18\x06 \x01(\tR\bquoteSumB\x16Z\x14../;cache_definitionb\x06proto3"

var (
	file_order_book_proto_rawDescOnce sync.Once
	file_order_book_proto_rawDescData []byte
)

func file_order_book_proto_rawDescGZIP() []byte {
	file_order_book_proto_rawDescOnce.Do(func() {
		file_order_book_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_order_book_proto_rawDesc), len(file_order_book_proto_rawDesc)))
	})
	return file_order_book_proto_rawDescData
}

var file_order_book_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_order_book_proto_goTypes = []any{
	(*OrderBookCacheDto)(nil),        // 0: OrderBookCacheDto
	(*OrderBookCacheDetailsDto)(nil), // 1: OrderBookCacheDetailsDto
	(*BlockInfoDto)(nil),             // 2: BlockInfoDto
}
var file_order_book_proto_depIdxs = []int32{
	2, // 0: OrderBookCacheDto.blockInfo:type_name -> BlockInfoDto
	1, // 1: OrderBookCacheDto.bids:type_name -> OrderBookCacheDetailsDto
	1, // 2: OrderBookCacheDto.asks:type_name -> OrderBookCacheDetailsDto
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_order_book_proto_init() }
func file_order_book_proto_init() {
	if File_order_book_proto != nil {
		return
	}
	file_common_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_order_book_proto_rawDesc), len(file_order_book_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_order_book_proto_goTypes,
		DependencyIndexes: file_order_book_proto_depIdxs,
		MessageInfos:      file_order_book_proto_msgTypes,
	}.Build()
	File_order_book_proto = out.File
	file_order_book_proto_goTypes = nil
	file_order_book_proto_depIdxs = nil
}
