// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: token_price.proto

package cache_definition

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenPriceCacheBySymbol struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Symbol                   string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	ImageUrl                 string                 `protobuf:"bytes,2,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	CurrentPrice             float32                `protobuf:"fixed32,3,opt,name=currentPrice,proto3" json:"currentPrice,omitempty"`
	PriceChangePercentage24H float32                `protobuf:"fixed32,4,opt,name=priceChangePercentage24H,proto3" json:"priceChangePercentage24H,omitempty"`
	UpdateTime               int64                  `protobuf:"varint,5,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	CoinId                   string                 `protobuf:"bytes,6,opt,name=coinId,proto3" json:"coinId,omitempty"`
	High24H                  float32                `protobuf:"fixed32,7,opt,name=high24h,proto3" json:"high24h,omitempty"`
	Low24H                   float32                `protobuf:"fixed32,8,opt,name=low24h,proto3" json:"low24h,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TokenPriceCacheBySymbol) Reset() {
	*x = TokenPriceCacheBySymbol{}
	mi := &file_token_price_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPriceCacheBySymbol) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPriceCacheBySymbol) ProtoMessage() {}

func (x *TokenPriceCacheBySymbol) ProtoReflect() protoreflect.Message {
	mi := &file_token_price_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPriceCacheBySymbol.ProtoReflect.Descriptor instead.
func (*TokenPriceCacheBySymbol) Descriptor() ([]byte, []int) {
	return file_token_price_proto_rawDescGZIP(), []int{0}
}

func (x *TokenPriceCacheBySymbol) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TokenPriceCacheBySymbol) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *TokenPriceCacheBySymbol) GetCurrentPrice() float32 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *TokenPriceCacheBySymbol) GetPriceChangePercentage24H() float32 {
	if x != nil {
		return x.PriceChangePercentage24H
	}
	return 0
}

func (x *TokenPriceCacheBySymbol) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *TokenPriceCacheBySymbol) GetCoinId() string {
	if x != nil {
		return x.CoinId
	}
	return ""
}

func (x *TokenPriceCacheBySymbol) GetHigh24H() float32 {
	if x != nil {
		return x.High24H
	}
	return 0
}

func (x *TokenPriceCacheBySymbol) GetLow24H() float32 {
	if x != nil {
		return x.Low24H
	}
	return 0
}

type TokenPriceCacheByAddress struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	Symbol                   string                 `protobuf:"bytes,1,opt,name=symbol,proto3" json:"symbol,omitempty"`
	ImageUrl                 string                 `protobuf:"bytes,2,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	CurrentPrice             float32                `protobuf:"fixed32,3,opt,name=currentPrice,proto3" json:"currentPrice,omitempty"`
	PriceChangePercentage24H float32                `protobuf:"fixed32,4,opt,name=priceChangePercentage24H,proto3" json:"priceChangePercentage24H,omitempty"`
	UpdateTime               int64                  `protobuf:"varint,5,opt,name=updateTime,proto3" json:"updateTime,omitempty"`
	ChainId                  uint64                 `protobuf:"varint,6,opt,name=chainId,proto3" json:"chainId,omitempty"`
	Address                  string                 `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	CoinId                   string                 `protobuf:"bytes,8,opt,name=coinId,proto3" json:"coinId,omitempty"`
	High24H                  float32                `protobuf:"fixed32,9,opt,name=high24h,proto3" json:"high24h,omitempty"`
	Low24H                   float32                `protobuf:"fixed32,10,opt,name=low24h,proto3" json:"low24h,omitempty"`
	Decimals                 uint64                 `protobuf:"varint,11,opt,name=decimals,proto3" json:"decimals,omitempty"`
	NativeTokenCoinId        string                 `protobuf:"bytes,12,opt,name=nativeTokenCoinId,proto3" json:"nativeTokenCoinId,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *TokenPriceCacheByAddress) Reset() {
	*x = TokenPriceCacheByAddress{}
	mi := &file_token_price_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenPriceCacheByAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenPriceCacheByAddress) ProtoMessage() {}

func (x *TokenPriceCacheByAddress) ProtoReflect() protoreflect.Message {
	mi := &file_token_price_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenPriceCacheByAddress.ProtoReflect.Descriptor instead.
func (*TokenPriceCacheByAddress) Descriptor() ([]byte, []int) {
	return file_token_price_proto_rawDescGZIP(), []int{1}
}

func (x *TokenPriceCacheByAddress) GetSymbol() string {
	if x != nil {
		return x.Symbol
	}
	return ""
}

func (x *TokenPriceCacheByAddress) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *TokenPriceCacheByAddress) GetCurrentPrice() float32 {
	if x != nil {
		return x.CurrentPrice
	}
	return 0
}

func (x *TokenPriceCacheByAddress) GetPriceChangePercentage24H() float32 {
	if x != nil {
		return x.PriceChangePercentage24H
	}
	return 0
}

func (x *TokenPriceCacheByAddress) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *TokenPriceCacheByAddress) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *TokenPriceCacheByAddress) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TokenPriceCacheByAddress) GetCoinId() string {
	if x != nil {
		return x.CoinId
	}
	return ""
}

func (x *TokenPriceCacheByAddress) GetHigh24H() float32 {
	if x != nil {
		return x.High24H
	}
	return 0
}

func (x *TokenPriceCacheByAddress) GetLow24H() float32 {
	if x != nil {
		return x.Low24H
	}
	return 0
}

func (x *TokenPriceCacheByAddress) GetDecimals() uint64 {
	if x != nil {
		return x.Decimals
	}
	return 0
}

func (x *TokenPriceCacheByAddress) GetNativeTokenCoinId() string {
	if x != nil {
		return x.NativeTokenCoinId
	}
	return ""
}

var File_token_price_proto protoreflect.FileDescriptor

const file_token_price_proto_rawDesc = "" +
	"\n" +
	"\x11token_price.proto\"\x97\x02\n" +
	"\x17TokenPriceCacheBySymbol\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bimageUrl\x18\x02 \x01(\tR\bimageUrl\x12\"\n" +
	"\fcurrentPrice\x18\x03 \x01(\x02R\fcurrentPrice\x12:\n" +
	"\x18priceChangePercentage24H\x18\x04 \x01(\x02R\x18priceChangePercentage24H\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x05 \x01(\x03R\n" +
	"updateTime\x12\x16\n" +
	"\x06coinId\x18\x06 \x01(\tR\x06coinId\x12\x18\n" +
	"\ahigh24h\x18\a \x01(\x02R\ahigh24h\x12\x16\n" +
	"\x06low24h\x18\b \x01(\x02R\x06low24h\"\x96\x03\n" +
	"\x18TokenPriceCacheByAddress\x12\x16\n" +
	"\x06symbol\x18\x01 \x01(\tR\x06symbol\x12\x1a\n" +
	"\bimageUrl\x18\x02 \x01(\tR\bimageUrl\x12\"\n" +
	"\fcurrentPrice\x18\x03 \x01(\x02R\fcurrentPrice\x12:\n" +
	"\x18priceChangePercentage24H\x18\x04 \x01(\x02R\x18priceChangePercentage24H\x12\x1e\n" +
	"\n" +
	"updateTime\x18\x05 \x01(\x03R\n" +
	"updateTime\x12\x18\n" +
	"\achainId\x18\x06 \x01(\x04R\achainId\x12\x18\n" +
	"\aaddress\x18\a \x01(\tR\aaddress\x12\x16\n" +
	"\x06coinId\x18\b \x01(\tR\x06coinId\x12\x18\n" +
	"\ahigh24h\x18\t \x01(\x02R\ahigh24h\x12\x16\n" +
	"\x06low24h\x18\n" +
	" \x01(\x02R\x06low24h\x12\x1a\n" +
	"\bdecimals\x18\v \x01(\x04R\bdecimals\x12,\n" +
	"\x11nativeTokenCoinId\x18\f \x01(\tR\x11nativeTokenCoinIdB\x16Z\x14../;cache_definitionb\x06proto3"

var (
	file_token_price_proto_rawDescOnce sync.Once
	file_token_price_proto_rawDescData []byte
)

func file_token_price_proto_rawDescGZIP() []byte {
	file_token_price_proto_rawDescOnce.Do(func() {
		file_token_price_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_token_price_proto_rawDesc), len(file_token_price_proto_rawDesc)))
	})
	return file_token_price_proto_rawDescData
}

var file_token_price_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_token_price_proto_goTypes = []any{
	(*TokenPriceCacheBySymbol)(nil),  // 0: TokenPriceCacheBySymbol
	(*TokenPriceCacheByAddress)(nil), // 1: TokenPriceCacheByAddress
}
var file_token_price_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_token_price_proto_init() }
func file_token_price_proto_init() {
	if File_token_price_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_token_price_proto_rawDesc), len(file_token_price_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_token_price_proto_goTypes,
		DependencyIndexes: file_token_price_proto_depIdxs,
		MessageInfos:      file_token_price_proto_msgTypes,
	}.Build()
	File_token_price_proto = out.File
	file_token_price_proto_goTypes = nil
	file_token_price_proto_depIdxs = nil
}
