// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: tx_service.proto

package tx_service

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Wallet types
type WalletType int32

const (
	WalletType_WALLET_TYPE_UNSPECIFIED   WalletType = 0
	WalletType_WALLET_TYPE_BACKEND_BOT   WalletType = 1
	WalletType_WALLET_TYPE_FRONTEND_USER WalletType = 2
)

// Enum value maps for WalletType.
var (
	WalletType_name = map[int32]string{
		0: "WALLET_TYPE_UNSPECIFIED",
		1: "WALLET_TYPE_BACKEND_BOT",
		2: "WALLET_TYPE_FRONTEND_USER",
	}
	WalletType_value = map[string]int32{
		"WALLET_TYPE_UNSPECIFIED":   0,
		"WALLET_TYPE_BACKEND_BOT":   1,
		"WALLET_TYPE_FRONTEND_USER": 2,
	}
)

func (x WalletType) Enum() *WalletType {
	p := new(WalletType)
	*p = x
	return p
}

func (x WalletType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WalletType) Descriptor() protoreflect.EnumDescriptor {
	return file_tx_service_proto_enumTypes[0].Descriptor()
}

func (WalletType) Type() protoreflect.EnumType {
	return &file_tx_service_proto_enumTypes[0]
}

func (x WalletType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WalletType.Descriptor instead.
func (WalletType) EnumDescriptor() ([]byte, []int) {
	return file_tx_service_proto_rawDescGZIP(), []int{0}
}

// Transaction status
type TransactionStatus int32

const (
	TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED TransactionStatus = 0
	TransactionStatus_TRANSACTION_STATUS_PENDING     TransactionStatus = 1
	TransactionStatus_TRANSACTION_STATUS_CONFIRMED   TransactionStatus = 2
	TransactionStatus_TRANSACTION_STATUS_FAILED      TransactionStatus = 3
)

// Enum value maps for TransactionStatus.
var (
	TransactionStatus_name = map[int32]string{
		0: "TRANSACTION_STATUS_UNSPECIFIED",
		1: "TRANSACTION_STATUS_PENDING",
		2: "TRANSACTION_STATUS_CONFIRMED",
		3: "TRANSACTION_STATUS_FAILED",
	}
	TransactionStatus_value = map[string]int32{
		"TRANSACTION_STATUS_UNSPECIFIED": 0,
		"TRANSACTION_STATUS_PENDING":     1,
		"TRANSACTION_STATUS_CONFIRMED":   2,
		"TRANSACTION_STATUS_FAILED":      3,
	}
)

func (x TransactionStatus) Enum() *TransactionStatus {
	p := new(TransactionStatus)
	*p = x
	return p
}

func (x TransactionStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransactionStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_tx_service_proto_enumTypes[1].Descriptor()
}

func (TransactionStatus) Type() protoreflect.EnumType {
	return &file_tx_service_proto_enumTypes[1]
}

func (x TransactionStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransactionStatus.Descriptor instead.
func (TransactionStatus) EnumDescriptor() ([]byte, []int) {
	return file_tx_service_proto_rawDescGZIP(), []int{1}
}

// Wallet message
type Wallet struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address       string                 `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,3,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	WalletType    WalletType             `protobuf:"varint,4,opt,name=wallet_type,json=walletType,proto3,enum=tx_service.WalletType" json:"wallet_type,omitempty"`
	Nonce         uint64                 `protobuf:"varint,5,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ChainId       uint64                 `protobuf:"varint,6,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,8,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Wallet) Reset() {
	*x = Wallet{}
	mi := &file_tx_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Wallet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Wallet) ProtoMessage() {}

func (x *Wallet) ProtoReflect() protoreflect.Message {
	mi := &file_tx_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Wallet.ProtoReflect.Descriptor instead.
func (*Wallet) Descriptor() ([]byte, []int) {
	return file_tx_service_proto_rawDescGZIP(), []int{0}
}

func (x *Wallet) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Wallet) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *Wallet) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *Wallet) GetWalletType() WalletType {
	if x != nil {
		return x.WalletType
	}
	return WalletType_WALLET_TYPE_UNSPECIFIED
}

func (x *Wallet) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Wallet) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Wallet) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Wallet) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

// Transaction message
type Transaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	WalletId      uint64                 `protobuf:"varint,2,opt,name=wallet_id,json=walletId,proto3" json:"wallet_id,omitempty"`
	RequestId     string                 `protobuf:"bytes,3,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ChainId       uint64                 `protobuf:"varint,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	TxHash        string                 `protobuf:"bytes,5,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	FromAddress   string                 `protobuf:"bytes,6,opt,name=from_address,json=fromAddress,proto3" json:"from_address,omitempty"`
	ToAddress     string                 `protobuf:"bytes,7,opt,name=to_address,json=toAddress,proto3" json:"to_address,omitempty"`
	Value         string                 `protobuf:"bytes,8,opt,name=value,proto3" json:"value,omitempty"`
	GasLimit      uint64                 `protobuf:"varint,9,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasPrice      string                 `protobuf:"bytes,10,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	Calldata      string                 `protobuf:"bytes,11,opt,name=calldata,proto3" json:"calldata,omitempty"`
	Nonce         uint64                 `protobuf:"varint,12,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Status        TransactionStatus      `protobuf:"varint,13,opt,name=status,proto3,enum=tx_service.TransactionStatus" json:"status,omitempty"`
	BlockNumber   *uint64                `protobuf:"varint,14,opt,name=block_number,json=blockNumber,proto3,oneof" json:"block_number,omitempty"`
	Receipt       string                 `protobuf:"bytes,15,opt,name=receipt,proto3" json:"receipt,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,16,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     int64                  `protobuf:"varint,17,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	Wallet        *Wallet                `protobuf:"bytes,18,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transaction) Reset() {
	*x = Transaction{}
	mi := &file_tx_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transaction) ProtoMessage() {}

func (x *Transaction) ProtoReflect() protoreflect.Message {
	mi := &file_tx_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transaction.ProtoReflect.Descriptor instead.
func (*Transaction) Descriptor() ([]byte, []int) {
	return file_tx_service_proto_rawDescGZIP(), []int{1}
}

func (x *Transaction) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Transaction) GetWalletId() uint64 {
	if x != nil {
		return x.WalletId
	}
	return 0
}

func (x *Transaction) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Transaction) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *Transaction) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *Transaction) GetFromAddress() string {
	if x != nil {
		return x.FromAddress
	}
	return ""
}

func (x *Transaction) GetToAddress() string {
	if x != nil {
		return x.ToAddress
	}
	return ""
}

func (x *Transaction) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *Transaction) GetGasLimit() uint64 {
	if x != nil {
		return x.GasLimit
	}
	return 0
}

func (x *Transaction) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *Transaction) GetCalldata() string {
	if x != nil {
		return x.Calldata
	}
	return ""
}

func (x *Transaction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *Transaction) GetStatus() TransactionStatus {
	if x != nil {
		return x.Status
	}
	return TransactionStatus_TRANSACTION_STATUS_UNSPECIFIED
}

func (x *Transaction) GetBlockNumber() uint64 {
	if x != nil && x.BlockNumber != nil {
		return *x.BlockNumber
	}
	return 0
}

func (x *Transaction) GetReceipt() string {
	if x != nil {
		return x.Receipt
	}
	return ""
}

func (x *Transaction) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Transaction) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

func (x *Transaction) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

// Register wallet request
type RegisterWalletRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Address       string                 `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	PrivateKey    string                 `protobuf:"bytes,2,opt,name=private_key,json=privateKey,proto3" json:"private_key,omitempty"`
	WalletType    WalletType             `protobuf:"varint,3,opt,name=wallet_type,json=walletType,proto3,enum=tx_service.WalletType" json:"wallet_type,omitempty"`
	ChainId       uint64                 `protobuf:"varint,4,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWalletRequest) Reset() {
	*x = RegisterWalletRequest{}
	mi := &file_tx_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWalletRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWalletRequest) ProtoMessage() {}

func (x *RegisterWalletRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWalletRequest.ProtoReflect.Descriptor instead.
func (*RegisterWalletRequest) Descriptor() ([]byte, []int) {
	return file_tx_service_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterWalletRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *RegisterWalletRequest) GetPrivateKey() string {
	if x != nil {
		return x.PrivateKey
	}
	return ""
}

func (x *RegisterWalletRequest) GetWalletType() WalletType {
	if x != nil {
		return x.WalletType
	}
	return WalletType_WALLET_TYPE_UNSPECIFIED
}

func (x *RegisterWalletRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

// Register wallet response
type RegisterWalletResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Wallet        *Wallet                `protobuf:"bytes,3,opt,name=wallet,proto3" json:"wallet,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterWalletResponse) Reset() {
	*x = RegisterWalletResponse{}
	mi := &file_tx_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterWalletResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterWalletResponse) ProtoMessage() {}

func (x *RegisterWalletResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterWalletResponse.ProtoReflect.Descriptor instead.
func (*RegisterWalletResponse) Descriptor() ([]byte, []int) {
	return file_tx_service_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterWalletResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegisterWalletResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterWalletResponse) GetWallet() *Wallet {
	if x != nil {
		return x.Wallet
	}
	return nil
}

// Update nonces from chain request
type UpdateNoncesFromChainRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MaxConcurrency int32                  `protobuf:"varint,1,opt,name=max_concurrency,json=maxConcurrency,proto3" json:"max_concurrency,omitempty"` // Maximum number of concurrent requests (default: 10)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateNoncesFromChainRequest) Reset() {
	*x = UpdateNoncesFromChainRequest{}
	mi := &file_tx_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoncesFromChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoncesFromChainRequest) ProtoMessage() {}

func (x *UpdateNoncesFromChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoncesFromChainRequest.ProtoReflect.Descriptor instead.
func (*UpdateNoncesFromChainRequest) Descriptor() ([]byte, []int) {
	return file_tx_service_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateNoncesFromChainRequest) GetMaxConcurrency() int32 {
	if x != nil {
		return x.MaxConcurrency
	}
	return 0
}

// Update nonces from chain response
type UpdateNoncesFromChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateNoncesFromChainResponse) Reset() {
	*x = UpdateNoncesFromChainResponse{}
	mi := &file_tx_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateNoncesFromChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateNoncesFromChainResponse) ProtoMessage() {}

func (x *UpdateNoncesFromChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateNoncesFromChainResponse.ProtoReflect.Descriptor instead.
func (*UpdateNoncesFromChainResponse) Descriptor() ([]byte, []int) {
	return file_tx_service_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateNoncesFromChainResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateNoncesFromChainResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Send transaction request
type SendTransactionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"` // Optional, will be generated if not provided
	WalletAddress string                 `protobuf:"bytes,2,opt,name=wallet_address,json=walletAddress,proto3" json:"wallet_address,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Calldata      string                 `protobuf:"bytes,5,opt,name=calldata,proto3" json:"calldata,omitempty"`
	GasLimit      string                 `protobuf:"bytes,6,opt,name=gas_limit,json=gasLimit,proto3" json:"gas_limit,omitempty"`
	GasPrice      string                 `protobuf:"bytes,7,opt,name=gas_price,json=gasPrice,proto3" json:"gas_price,omitempty"`
	ChainId       uint64                 `protobuf:"varint,8,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTransactionRequest) Reset() {
	*x = SendTransactionRequest{}
	mi := &file_tx_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionRequest) ProtoMessage() {}

func (x *SendTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionRequest.ProtoReflect.Descriptor instead.
func (*SendTransactionRequest) Descriptor() ([]byte, []int) {
	return file_tx_service_proto_rawDescGZIP(), []int{6}
}

func (x *SendTransactionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *SendTransactionRequest) GetWalletAddress() string {
	if x != nil {
		return x.WalletAddress
	}
	return ""
}

func (x *SendTransactionRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *SendTransactionRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *SendTransactionRequest) GetCalldata() string {
	if x != nil {
		return x.Calldata
	}
	return ""
}

func (x *SendTransactionRequest) GetGasLimit() string {
	if x != nil {
		return x.GasLimit
	}
	return ""
}

func (x *SendTransactionRequest) GetGasPrice() string {
	if x != nil {
		return x.GasPrice
	}
	return ""
}

func (x *SendTransactionRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

// Send transaction response
type SendTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Transaction   *Transaction           `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendTransactionResponse) Reset() {
	*x = SendTransactionResponse{}
	mi := &file_tx_service_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendTransactionResponse) ProtoMessage() {}

func (x *SendTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_service_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendTransactionResponse.ProtoReflect.Descriptor instead.
func (*SendTransactionResponse) Descriptor() ([]byte, []int) {
	return file_tx_service_proto_rawDescGZIP(), []int{7}
}

func (x *SendTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *SendTransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *SendTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

// Get transaction request - supports query by tx_hash or request_id
type GetTransactionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Query:
	//
	//	*GetTransactionRequest_TxHash
	//	*GetTransactionRequest_RequestId
	Query         isGetTransactionRequest_Query `protobuf_oneof:"query"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionRequest) Reset() {
	*x = GetTransactionRequest{}
	mi := &file_tx_service_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionRequest) ProtoMessage() {}

func (x *GetTransactionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_tx_service_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionRequest.ProtoReflect.Descriptor instead.
func (*GetTransactionRequest) Descriptor() ([]byte, []int) {
	return file_tx_service_proto_rawDescGZIP(), []int{8}
}

func (x *GetTransactionRequest) GetQuery() isGetTransactionRequest_Query {
	if x != nil {
		return x.Query
	}
	return nil
}

func (x *GetTransactionRequest) GetTxHash() string {
	if x != nil {
		if x, ok := x.Query.(*GetTransactionRequest_TxHash); ok {
			return x.TxHash
		}
	}
	return ""
}

func (x *GetTransactionRequest) GetRequestId() string {
	if x != nil {
		if x, ok := x.Query.(*GetTransactionRequest_RequestId); ok {
			return x.RequestId
		}
	}
	return ""
}

type isGetTransactionRequest_Query interface {
	isGetTransactionRequest_Query()
}

type GetTransactionRequest_TxHash struct {
	TxHash string `protobuf:"bytes,1,opt,name=tx_hash,json=txHash,proto3,oneof"`
}

type GetTransactionRequest_RequestId struct {
	RequestId string `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3,oneof"`
}

func (*GetTransactionRequest_TxHash) isGetTransactionRequest_Query() {}

func (*GetTransactionRequest_RequestId) isGetTransactionRequest_Query() {}

// Get transaction response
type GetTransactionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Transaction   *Transaction           `protobuf:"bytes,3,opt,name=transaction,proto3" json:"transaction,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTransactionResponse) Reset() {
	*x = GetTransactionResponse{}
	mi := &file_tx_service_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTransactionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTransactionResponse) ProtoMessage() {}

func (x *GetTransactionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_tx_service_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTransactionResponse.ProtoReflect.Descriptor instead.
func (*GetTransactionResponse) Descriptor() ([]byte, []int) {
	return file_tx_service_proto_rawDescGZIP(), []int{9}
}

func (x *GetTransactionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetTransactionResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetTransactionResponse) GetTransaction() *Transaction {
	if x != nil {
		return x.Transaction
	}
	return nil
}

var File_tx_service_proto protoreflect.FileDescriptor

const file_tx_service_proto_rawDesc = "" +
	"\n" +
	"\x10tx_service.proto\x12\n" +
	"tx_service\"\xfb\x01\n" +
	"\x06Wallet\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x18\n" +
	"\aaddress\x18\x02 \x01(\tR\aaddress\x12\x1f\n" +
	"\vprivate_key\x18\x03 \x01(\tR\n" +
	"privateKey\x127\n" +
	"\vwallet_type\x18\x04 \x01(\x0e2\x16.tx_service.WalletTypeR\n" +
	"walletType\x12\x14\n" +
	"\x05nonce\x18\x05 \x01(\x04R\x05nonce\x12\x19\n" +
	"\bchain_id\x18\x06 \x01(\x04R\achainId\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\b \x01(\x03R\tupdatedAt\"\xc5\x04\n" +
	"\vTransaction\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\twallet_id\x18\x02 \x01(\x04R\bwalletId\x12\x1d\n" +
	"\n" +
	"request_id\x18\x03 \x01(\tR\trequestId\x12\x19\n" +
	"\bchain_id\x18\x04 \x01(\x04R\achainId\x12\x17\n" +
	"\atx_hash\x18\x05 \x01(\tR\x06txHash\x12!\n" +
	"\ffrom_address\x18\x06 \x01(\tR\vfromAddress\x12\x1d\n" +
	"\n" +
	"to_address\x18\a \x01(\tR\ttoAddress\x12\x14\n" +
	"\x05value\x18\b \x01(\tR\x05value\x12\x1b\n" +
	"\tgas_limit\x18\t \x01(\x04R\bgasLimit\x12\x1b\n" +
	"\tgas_price\x18\n" +
	" \x01(\tR\bgasPrice\x12\x1a\n" +
	"\bcalldata\x18\v \x01(\tR\bcalldata\x12\x14\n" +
	"\x05nonce\x18\f \x01(\x04R\x05nonce\x125\n" +
	"\x06status\x18\r \x01(\x0e2\x1d.tx_service.TransactionStatusR\x06status\x12&\n" +
	"\fblock_number\x18\x0e \x01(\x04H\x00R\vblockNumber\x88\x01\x01\x12\x18\n" +
	"\areceipt\x18\x0f \x01(\tR\areceipt\x12\x1d\n" +
	"\n" +
	"created_at\x18\x10 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x11 \x01(\x03R\tupdatedAt\x12*\n" +
	"\x06wallet\x18\x12 \x01(\v2\x12.tx_service.WalletR\x06walletB\x0f\n" +
	"\r_block_number\"\xa6\x01\n" +
	"\x15RegisterWalletRequest\x12\x18\n" +
	"\aaddress\x18\x01 \x01(\tR\aaddress\x12\x1f\n" +
	"\vprivate_key\x18\x02 \x01(\tR\n" +
	"privateKey\x127\n" +
	"\vwallet_type\x18\x03 \x01(\x0e2\x16.tx_service.WalletTypeR\n" +
	"walletType\x12\x19\n" +
	"\bchain_id\x18\x04 \x01(\x04R\achainId\"x\n" +
	"\x16RegisterWalletResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12*\n" +
	"\x06wallet\x18\x03 \x01(\v2\x12.tx_service.WalletR\x06wallet\"G\n" +
	"\x1cUpdateNoncesFromChainRequest\x12'\n" +
	"\x0fmax_concurrency\x18\x01 \x01(\x05R\x0emaxConcurrency\"S\n" +
	"\x1dUpdateNoncesFromChainResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xf5\x01\n" +
	"\x16SendTransactionRequest\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x12%\n" +
	"\x0ewallet_address\x18\x02 \x01(\tR\rwalletAddress\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x1a\n" +
	"\bcalldata\x18\x05 \x01(\tR\bcalldata\x12\x1b\n" +
	"\tgas_limit\x18\x06 \x01(\tR\bgasLimit\x12\x1b\n" +
	"\tgas_price\x18\a \x01(\tR\bgasPrice\x12\x19\n" +
	"\bchain_id\x18\b \x01(\x04R\achainId\"\x88\x01\n" +
	"\x17SendTransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\vtransaction\x18\x03 \x01(\v2\x17.tx_service.TransactionR\vtransaction\"\\\n" +
	"\x15GetTransactionRequest\x12\x19\n" +
	"\atx_hash\x18\x01 \x01(\tH\x00R\x06txHash\x12\x1f\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tH\x00R\trequestIdB\a\n" +
	"\x05query\"\x87\x01\n" +
	"\x16GetTransactionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x129\n" +
	"\vtransaction\x18\x03 \x01(\v2\x17.tx_service.TransactionR\vtransaction*e\n" +
	"\n" +
	"WalletType\x12\x1b\n" +
	"\x17WALLET_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17WALLET_TYPE_BACKEND_BOT\x10\x01\x12\x1d\n" +
	"\x19WALLET_TYPE_FRONTEND_USER\x10\x02*\x98\x01\n" +
	"\x11TransactionStatus\x12\"\n" +
	"\x1eTRANSACTION_STATUS_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aTRANSACTION_STATUS_PENDING\x10\x01\x12 \n" +
	"\x1cTRANSACTION_STATUS_CONFIRMED\x10\x02\x12\x1d\n" +
	"\x19TRANSACTION_STATUS_FAILED\x10\x032\x87\x03\n" +
	"\tTxService\x12W\n" +
	"\x0eRegisterWallet\x12!.tx_service.RegisterWalletRequest\x1a\".tx_service.RegisterWalletResponse\x12l\n" +
	"\x15UpdateNoncesFromChain\x12(.tx_service.UpdateNoncesFromChainRequest\x1a).tx_service.UpdateNoncesFromChainResponse\x12Z\n" +
	"\x0fSendTransaction\x12\".tx_service.SendTransactionRequest\x1a#.tx_service.SendTransactionResponse\x12W\n" +
	"\x0eGetTransaction\x12!.tx_service.GetTransactionRequest\x1a\".tx_service.GetTransactionResponseB\x10Z\x0e../;tx_serviceb\x06proto3"

var (
	file_tx_service_proto_rawDescOnce sync.Once
	file_tx_service_proto_rawDescData []byte
)

func file_tx_service_proto_rawDescGZIP() []byte {
	file_tx_service_proto_rawDescOnce.Do(func() {
		file_tx_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_tx_service_proto_rawDesc), len(file_tx_service_proto_rawDesc)))
	})
	return file_tx_service_proto_rawDescData
}

var file_tx_service_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_tx_service_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_tx_service_proto_goTypes = []any{
	(WalletType)(0),                       // 0: tx_service.WalletType
	(TransactionStatus)(0),                // 1: tx_service.TransactionStatus
	(*Wallet)(nil),                        // 2: tx_service.Wallet
	(*Transaction)(nil),                   // 3: tx_service.Transaction
	(*RegisterWalletRequest)(nil),         // 4: tx_service.RegisterWalletRequest
	(*RegisterWalletResponse)(nil),        // 5: tx_service.RegisterWalletResponse
	(*UpdateNoncesFromChainRequest)(nil),  // 6: tx_service.UpdateNoncesFromChainRequest
	(*UpdateNoncesFromChainResponse)(nil), // 7: tx_service.UpdateNoncesFromChainResponse
	(*SendTransactionRequest)(nil),        // 8: tx_service.SendTransactionRequest
	(*SendTransactionResponse)(nil),       // 9: tx_service.SendTransactionResponse
	(*GetTransactionRequest)(nil),         // 10: tx_service.GetTransactionRequest
	(*GetTransactionResponse)(nil),        // 11: tx_service.GetTransactionResponse
}
var file_tx_service_proto_depIdxs = []int32{
	0,  // 0: tx_service.Wallet.wallet_type:type_name -> tx_service.WalletType
	1,  // 1: tx_service.Transaction.status:type_name -> tx_service.TransactionStatus
	2,  // 2: tx_service.Transaction.wallet:type_name -> tx_service.Wallet
	0,  // 3: tx_service.RegisterWalletRequest.wallet_type:type_name -> tx_service.WalletType
	2,  // 4: tx_service.RegisterWalletResponse.wallet:type_name -> tx_service.Wallet
	3,  // 5: tx_service.SendTransactionResponse.transaction:type_name -> tx_service.Transaction
	3,  // 6: tx_service.GetTransactionResponse.transaction:type_name -> tx_service.Transaction
	4,  // 7: tx_service.TxService.RegisterWallet:input_type -> tx_service.RegisterWalletRequest
	6,  // 8: tx_service.TxService.UpdateNoncesFromChain:input_type -> tx_service.UpdateNoncesFromChainRequest
	8,  // 9: tx_service.TxService.SendTransaction:input_type -> tx_service.SendTransactionRequest
	10, // 10: tx_service.TxService.GetTransaction:input_type -> tx_service.GetTransactionRequest
	5,  // 11: tx_service.TxService.RegisterWallet:output_type -> tx_service.RegisterWalletResponse
	7,  // 12: tx_service.TxService.UpdateNoncesFromChain:output_type -> tx_service.UpdateNoncesFromChainResponse
	9,  // 13: tx_service.TxService.SendTransaction:output_type -> tx_service.SendTransactionResponse
	11, // 14: tx_service.TxService.GetTransaction:output_type -> tx_service.GetTransactionResponse
	11, // [11:15] is the sub-list for method output_type
	7,  // [7:11] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_tx_service_proto_init() }
func file_tx_service_proto_init() {
	if File_tx_service_proto != nil {
		return
	}
	file_tx_service_proto_msgTypes[1].OneofWrappers = []any{}
	file_tx_service_proto_msgTypes[8].OneofWrappers = []any{
		(*GetTransactionRequest_TxHash)(nil),
		(*GetTransactionRequest_RequestId)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_tx_service_proto_rawDesc), len(file_tx_service_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_tx_service_proto_goTypes,
		DependencyIndexes: file_tx_service_proto_depIdxs,
		EnumInfos:         file_tx_service_proto_enumTypes,
		MessageInfos:      file_tx_service_proto_msgTypes,
	}.Build()
	File_tx_service_proto = out.File
	file_tx_service_proto_goTypes = nil
	file_tx_service_proto_depIdxs = nil
}
